//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AttDefineData.proto
namespace AttDefineData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllAttDefineData")]
  public partial class AllAttDefineData : global::ProtoBuf.IExtensible
  {
    public AllAttDefineData() {}
    
    private readonly global::System.Collections.Generic.List<AttDefineData> _tlist = new global::System.Collections.Generic.List<AttDefineData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AttDefineData> tlist
    {
      get { return _tlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttDefineData")]
  public partial class AttDefineData : global::ProtoBuf.IExtensible
  {
    public AttDefineData() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _ui_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ui_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ui_name
    {
      get { return _ui_name; }
      set { _ui_name = value; }
    }
    private string _tips = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tips
    {
      get { return _tips; }
      set { _tips = value; }
    }
    private int _fight_value = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fight_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fight_value
    {
      get { return _fight_value; }
      set { _fight_value = value; }
    }
    private int _div_value = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"div_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int div_value
    {
      get { return _div_value; }
      set { _div_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}