//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BaseAtt.proto
// Note: requires additional types generated from: EquipmentAtt.EquipmentAtt.proto
namespace BaseAtt
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaseAtt")]
  public partial class BaseAtt : global::ProtoBuf.IExtensible
  {
    public BaseAtt() {}
    
    private long _roleID = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long roleID
    {
      get { return _roleID; }
      set { _roleID = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _profession = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"profession", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int profession
    {
      get { return _profession; }
      set { _profession = value; }
    }
    private EquipmentAtt.EquipmentAtt _equipAtt = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"equipAtt", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public EquipmentAtt.EquipmentAtt equipAtt
    {
      get { return _equipAtt; }
      set { _equipAtt = value; }
    }
    private float _height = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float height
    {
      get { return _height; }
      set { _height = value; }
    }
    private float _effHeight = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"effHeight", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float effHeight
    {
      get { return _effHeight; }
      set { _effHeight = value; }
    }
    private string _avatar = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private int _level = (int)1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private float _width = (float)1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1)]
    public float width
    {
      get { return _width; }
      set { _width = value; }
    }
    private int _physique = (int)-1;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"physique", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int physique
    {
      get { return _physique; }
      set { _physique = value; }
    }
    private bool _male = default(bool);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"male", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool male
    {
      get { return _male; }
      set { _male = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}