//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ConfigData.proto
namespace ConfigData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllConfigData")]
  public partial class AllConfigData : global::ProtoBuf.IExtensible
  {
    public AllConfigData() {}
    
    private readonly global::System.Collections.Generic.List<ConfigData> _tlist = new global::System.Collections.Generic.List<ConfigData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ConfigData> tlist
    {
      get { return _tlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConfigData")]
  public partial class ConfigData : global::ProtoBuf.IExtensible
  {
    public ConfigData() {}
    
    private int _key = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int key
    {
      get { return _key; }
      set { _key = value; }
    }
    private int _intValue = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"intValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int intValue
    {
      get { return _intValue; }
      set { _intValue = value; }
    }
    private string _stringValue = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stringValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stringValue
    {
      get { return _stringValue; }
      set { _stringValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}