//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EffectConfig.proto
// Note: requires additional types generated from: Math.proto
// Note: requires additional types generated from: StringID.proto
using Math;
using StringID;

namespace EffectConfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EffectConfig")]
  public partial class EffectConfig : global::ProtoBuf.IExtensible
  {
    public EffectConfig() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _effectName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"effectName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string effectName
    {
      get { return _effectName; }
      set { _effectName = value; }
    }
    private EffectConfig.PosType _posType = EffectConfig.PosType.FEET;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"posType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(EffectConfig.PosType.FEET)]
    public EffectConfig.PosType posType
    {
      get { return _posType; }
      set { _posType = value; }
    }
    private Vector3f _position = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f position
    {
      get { return _position; }
      set { _position = value; }
    }
    private string _boneName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"boneName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string boneName
    {
      get { return _boneName; }
      set { _boneName = value; }
    }
    private EffectConfig.LifeTime _lifeTime = EffectConfig.LifeTime.AUTO;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"lifeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(EffectConfig.LifeTime.AUTO)]
    public EffectConfig.LifeTime lifeTime
    {
      get { return _lifeTime; }
      set { _lifeTime = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"LifeTime")]
    public enum LifeTime
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AUTO", Value=0)]
      AUTO = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GLOBAL", Value=1)]
      GLOBAL = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PosType")]
    public enum PosType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FEET", Value=0)]
      FEET = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BODY", Value=1)]
      BODY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEAD", Value=2)]
      HEAD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BONE", Value=3)]
      BONE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RELATIVE", Value=4)]
      RELATIVE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WORLD", Value=5)]
      WORLD = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllEffectConfig")]
  public partial class AllEffectConfig : global::ProtoBuf.IExtensible
  {
    public AllEffectConfig() {}
    
    private readonly global::System.Collections.Generic.List<EffectConfig> _effects = new global::System.Collections.Generic.List<EffectConfig>();
    [global::ProtoBuf.ProtoMember(1, Name=@"effects", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EffectConfig> effects
    {
      get { return _effects; }
    }
  
    private AllStringID _stringID = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stringID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AllStringID stringID
    {
      get { return _stringID; }
      set { _stringID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}