//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EquipmentInfo.proto
// Note: requires additional types generated from: StringID.proto
using StringID;

namespace EquipmentInfo
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttachValue")]
  public partial class AttachValue : global::ProtoBuf.IExtensible
  {
    public AttachValue() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _onePropertyBasicMin = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"onePropertyBasicMin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> onePropertyBasicMin
    {
      get { return _onePropertyBasicMin; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _onePropertyBasicMax = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"onePropertyBasicMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> onePropertyBasicMax
    {
      get { return _onePropertyBasicMax; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _onePropertyRatioMin = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(4, Name=@"onePropertyRatioMin", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> onePropertyRatioMin
    {
      get { return _onePropertyRatioMin; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _onePropertyRatioMax = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(5, Name=@"onePropertyRatioMax", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> onePropertyRatioMax
    {
      get { return _onePropertyRatioMax; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _onePropertyAttachMin = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"onePropertyAttachMin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> onePropertyAttachMin
    {
      get { return _onePropertyAttachMin; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _onePropertyAttachMax = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"onePropertyAttachMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> onePropertyAttachMax
    {
      get { return _onePropertyAttachMax; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _twoPropertyBasicMin = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"twoPropertyBasicMin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> twoPropertyBasicMin
    {
      get { return _twoPropertyBasicMin; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _twoPropertyBasicMax = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"twoPropertyBasicMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> twoPropertyBasicMax
    {
      get { return _twoPropertyBasicMax; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _twoPropertyRatioMin = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(10, Name=@"twoPropertyRatioMin", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> twoPropertyRatioMin
    {
      get { return _twoPropertyRatioMin; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _twoPropertyRatioMax = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(11, Name=@"twoPropertyRatioMax", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> twoPropertyRatioMax
    {
      get { return _twoPropertyRatioMax; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _twoPropertyAttachMin = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"twoPropertyAttachMin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> twoPropertyAttachMin
    {
      get { return _twoPropertyAttachMin; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _twoPropertyAttachMax = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(13, Name=@"twoPropertyAttachMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> twoPropertyAttachMax
    {
      get { return _twoPropertyAttachMax; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _twoPropertyGloblRatioMin = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(14, Name=@"twoPropertyGloblRatioMin", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> twoPropertyGloblRatioMin
    {
      get { return _twoPropertyGloblRatioMin; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _twoPropertyGloblRatioMax = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(15, Name=@"twoPropertyGloblRatioMax", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> twoPropertyGloblRatioMax
    {
      get { return _twoPropertyGloblRatioMax; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _special_int_listMin = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(16, Name=@"special_int_listMin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> special_int_listMin
    {
      get { return _special_int_listMin; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _special_int_listMax = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(17, Name=@"special_int_listMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> special_int_listMax
    {
      get { return _special_int_listMax; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _special_float_listMin = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(18, Name=@"special_float_listMin", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> special_float_listMin
    {
      get { return _special_float_listMin; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _special_float_listMax = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(19, Name=@"special_float_listMax", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> special_float_listMax
    {
      get { return _special_float_listMax; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _onePropertyInitMin = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(20, Name=@"onePropertyInitMin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> onePropertyInitMin
    {
      get { return _onePropertyInitMin; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _onePropertyInitMax = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(21, Name=@"onePropertyInitMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> onePropertyInitMax
    {
      get { return _onePropertyInitMax; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _onePropertyGrowUpMin = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(22, Name=@"onePropertyGrowUpMin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> onePropertyGrowUpMin
    {
      get { return _onePropertyGrowUpMin; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _onePropertyGrowUpMax = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(23, Name=@"onePropertyGrowUpMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> onePropertyGrowUpMax
    {
      get { return _onePropertyGrowUpMax; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllAttachValues")]
  public partial class AllAttachValues : global::ProtoBuf.IExtensible
  {
    public AllAttachValues() {}
    
    private readonly global::System.Collections.Generic.List<AttachValue> _values = new global::System.Collections.Generic.List<AttachValue>();
    [global::ProtoBuf.ProtoMember(1, Name=@"values", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AttachValue> values
    {
      get { return _values; }
    }
  
    private AllStringID _stringID = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stringID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AllStringID stringID
    {
      get { return _stringID; }
      set { _stringID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttachProperty")]
  public partial class AttachProperty : global::ProtoBuf.IExtensible
  {
    public AttachProperty() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _propertyID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"propertyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> propertyID
    {
      get { return _propertyID; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _probability = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"probability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> probability
    {
      get { return _probability; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllAttachProperties")]
  public partial class AllAttachProperties : global::ProtoBuf.IExtensible
  {
    public AllAttachProperties() {}
    
    private readonly global::System.Collections.Generic.List<AttachProperty> _properties = new global::System.Collections.Generic.List<AttachProperty>();
    [global::ProtoBuf.ProtoMember(1, Name=@"properties", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AttachProperty> properties
    {
      get { return _properties; }
    }
  
    private AllStringID _stringID = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stringID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AllStringID stringID
    {
      get { return _stringID; }
      set { _stringID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipmentInfo")]
  public partial class EquipmentInfo : global::ProtoBuf.IExtensible
  {
    public EquipmentInfo() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _model = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"model", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string model
    {
      get { return _model; }
      set { _model = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _propertyBaseID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"propertyBaseID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> propertyBaseID
    {
      get { return _propertyBaseID; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _propertyBaseMin = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"propertyBaseMin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> propertyBaseMin
    {
      get { return _propertyBaseMin; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _propertyBaseMax = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"propertyBaseMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> propertyBaseMax
    {
      get { return _propertyBaseMax; }
    }
  
    private int _propertyAttachID = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"propertyAttachID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int propertyAttachID
    {
      get { return _propertyAttachID; }
      set { _propertyAttachID = value; }
    }
    private int _propertyAttachMin = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"propertyAttachMin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int propertyAttachMin
    {
      get { return _propertyAttachMin; }
      set { _propertyAttachMin = value; }
    }
    private int _propertyAttachMax = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"propertyAttachMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int propertyAttachMax
    {
      get { return _propertyAttachMax; }
      set { _propertyAttachMax = value; }
    }
    private int _propertyAttachValueID = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"propertyAttachValueID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int propertyAttachValueID
    {
      get { return _propertyAttachValueID; }
      set { _propertyAttachValueID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllEquipments")]
  public partial class AllEquipments : global::ProtoBuf.IExtensible
  {
    public AllEquipments() {}
    
    private readonly global::System.Collections.Generic.List<EquipmentInfo> _equips = new global::System.Collections.Generic.List<EquipmentInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EquipmentInfo> equips
    {
      get { return _equips; }
    }
  
    private AllStringID _stringID = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stringID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AllStringID stringID
    {
      get { return _stringID; }
      set { _stringID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}