//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Map.proto
// Note: requires additional types generated from: Math.proto
// Note: requires additional types generated from: Event.proto
// Note: requires additional types generated from: Item.Item.proto
// Note: requires additional types generated from: MapAnimation.MapAnimation.proto
using Event;
using Math;

namespace Map
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TransmitNode")]
  public partial class TransmitNode : global::ProtoBuf.IExtensible
  {
    public TransmitNode() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _map = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"map", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int map
    {
      get { return _map; }
      set { _map = value; }
    }
    private int _node = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"node", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int node
    {
      get { return _node; }
      set { _node = value; }
    }
    private Vector3f _position = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f position
    {
      get { return _position; }
      set { _position = value; }
    }
    private int _jumpGroup = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"jumpGroup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int jumpGroup
    {
      get { return _jumpGroup; }
      set { _jumpGroup = value; }
    }
    private string _eff = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"eff", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string eff
    {
      get { return _eff; }
      set { _eff = value; }
    }
    private Vector3f _rotation = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JumpNode")]
  public partial class JumpNode : global::ProtoBuf.IExtensible
  {
    public JumpNode() {}
    
    private int _next = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"next", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int next
    {
      get { return _next; }
      set { _next = value; }
    }
    private Vector3f _position = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f position
    {
      get { return _position; }
      set { _position = value; }
    }
    private Vector3f _rotation = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private float _cameraDistance = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cameraDistance", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float cameraDistance
    {
      get { return _cameraDistance; }
      set { _cameraDistance = value; }
    }
    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private bool _uniformSpeed = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"uniformSpeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool uniformSpeed
    {
      get { return _uniformSpeed; }
      set { _uniformSpeed = value; }
    }
    private int _delay = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"delay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int delay
    {
      get { return _delay; }
      set { _delay = value; }
    }
    private string _animBegin = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"animBegin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string animBegin
    {
      get { return _animBegin; }
      set { _animBegin = value; }
    }
    private string _animMove = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"animMove", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string animMove
    {
      get { return _animMove; }
      set { _animMove = value; }
    }
    private string _animOver = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"animOver", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string animOver
    {
      get { return _animOver; }
      set { _animOver = value; }
    }
    private Vector3f _towardDir = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"towardDir", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f towardDir
    {
      get { return _towardDir; }
      set { _towardDir = value; }
    }
    private int _animBeginTime = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"animBeginTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int animBeginTime
    {
      get { return _animBeginTime; }
      set { _animBeginTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JumpGroup")]
  public partial class JumpGroup : global::ProtoBuf.IExtensible
  {
    public JumpGroup() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<JumpNode> _jumpNodes = new global::System.Collections.Generic.List<JumpNode>();
    [global::ProtoBuf.ProtoMember(2, Name=@"jumpNodes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<JumpNode> jumpNodes
    {
      get { return _jumpNodes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NPCUnit")]
  public partial class NPCUnit : global::ProtoBuf.IExtensible
  {
    public NPCUnit() {}
    
    private int _resID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"resID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int resID
    {
      get { return _resID; }
      set { _resID = value; }
    }
    private Vector3f _position = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f position
    {
      get { return _position; }
      set { _position = value; }
    }
    private Vector3f _rotation = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private int _selfFaction = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"selfFaction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int selfFaction
    {
      get { return _selfFaction; }
      set { _selfFaction = value; }
    }
    private int _friendFaction = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"friendFaction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int friendFaction
    {
      get { return _friendFaction; }
      set { _friendFaction = value; }
    }
    private int _npcID = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"npcID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int npcID
    {
      get { return _npcID; }
      set { _npcID = value; }
    }
    private int _npcGroupId = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"npcGroupId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int npcGroupId
    {
      get { return _npcGroupId; }
      set { _npcGroupId = value; }
    }
    private MapAnimation.MapAnimation _bornAnimation = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"bornAnimation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapAnimation.MapAnimation bornAnimation
    {
      get { return _bornAnimation; }
      set { _bornAnimation = value; }
    }
    private MapAnimation.MapAnimation _dieAnimation = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"dieAnimation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapAnimation.MapAnimation dieAnimation
    {
      get { return _dieAnimation; }
      set { _dieAnimation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NPCPass")]
  public partial class NPCPass : global::ProtoBuf.IExtensible
  {
    public NPCPass() {}
    
    private int _delayTime = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"delayTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int delayTime
    {
      get { return _delayTime; }
      set { _delayTime = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _npcs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"npcs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> npcs
    {
      get { return _npcs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NPCGroup")]
  public partial class NPCGroup : global::ProtoBuf.IExtensible
  {
    public NPCGroup() {}
    
    private int _delayTime = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"delayTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int delayTime
    {
      get { return _delayTime; }
      set { _delayTime = value; }
    }
    private readonly global::System.Collections.Generic.List<NPCPass> _passes = new global::System.Collections.Generic.List<NPCPass>();
    [global::ProtoBuf.ProtoMember(2, Name=@"passes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NPCPass> passes
    {
      get { return _passes; }
    }
  
    private int _nextGroup = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nextGroup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nextGroup
    {
      get { return _nextGroup; }
      set { _nextGroup = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScenePathNodeContext")]
  public partial class ScenePathNodeContext : global::ProtoBuf.IExtensible
  {
    public ScenePathNodeContext() {}
    
    private int _cid = (int)-1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int cid
    {
      get { return _cid; }
      set { _cid = value; }
    }
    private float _cost = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cost", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float cost
    {
      get { return _cost; }
      set { _cost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScenePathNode")]
  public partial class ScenePathNode : global::ProtoBuf.IExtensible
  {
    public ScenePathNode() {}
    
    private int _id = (int)-1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private Vector3f _pos = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private readonly global::System.Collections.Generic.List<ScenePathNodeContext> _adjacentNodes = new global::System.Collections.Generic.List<ScenePathNodeContext>();
    [global::ProtoBuf.ProtoMember(3, Name=@"adjacentNodes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ScenePathNodeContext> adjacentNodes
    {
      get { return _adjacentNodes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScenePath")]
  public partial class ScenePath : global::ProtoBuf.IExtensible
  {
    public ScenePath() {}
    
    private readonly global::System.Collections.Generic.List<ScenePathNode> _nodes = new global::System.Collections.Generic.List<ScenePathNode>();
    [global::ProtoBuf.ProtoMember(1, Name=@"nodes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ScenePathNode> nodes
    {
      get { return _nodes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapUnit")]
  public partial class MapUnit : global::ProtoBuf.IExtensible
  {
    public MapUnit() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _resID = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resID
    {
      get { return _resID; }
      set { _resID = value; }
    }
    private readonly global::System.Collections.Generic.List<NPCUnit> _npcs = new global::System.Collections.Generic.List<NPCUnit>();
    [global::ProtoBuf.ProtoMember(3, Name=@"npcs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NPCUnit> npcs
    {
      get { return _npcs; }
    }
  
    private readonly global::System.Collections.Generic.List<TransmitNode> _transmitNodes = new global::System.Collections.Generic.List<TransmitNode>();
    [global::ProtoBuf.ProtoMember(4, Name=@"transmitNodes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TransmitNode> transmitNodes
    {
      get { return _transmitNodes; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _playSelfFactions = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"playSelfFactions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> playSelfFactions
    {
      get { return _playSelfFactions; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _playFriendFactions = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"playFriendFactions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> playFriendFactions
    {
      get { return _playFriendFactions; }
    }
  
    private readonly global::System.Collections.Generic.List<NPCGroup> _groups = new global::System.Collections.Generic.List<NPCGroup>();
    [global::ProtoBuf.ProtoMember(7, Name=@"groups", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<NPCGroup> groups
    {
      get { return _groups; }
    }
  
    private readonly global::System.Collections.Generic.List<JumpGroup> _jumpGroups = new global::System.Collections.Generic.List<JumpGroup>();
    [global::ProtoBuf.ProtoMember(8, Name=@"jumpGroups", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<JumpGroup> jumpGroups
    {
      get { return _jumpGroups; }
    }
  
    private readonly global::System.Collections.Generic.List<EventCondition> _eventCondition = new global::System.Collections.Generic.List<EventCondition>();
    [global::ProtoBuf.ProtoMember(9, Name=@"eventCondition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EventCondition> eventCondition
    {
      get { return _eventCondition; }
    }
  
    private readonly global::System.Collections.Generic.List<EventData> _eventData = new global::System.Collections.Generic.List<EventData>();
    [global::ProtoBuf.ProtoMember(10, Name=@"eventData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EventData> eventData
    {
      get { return _eventData; }
    }
  
    private ScenePath _scenePath = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"scenePath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ScenePath scenePath
    {
      get { return _scenePath; }
      set { _scenePath = value; }
    }
    private readonly global::System.Collections.Generic.List<MapAnimation.MapAnimation> _animations = new global::System.Collections.Generic.List<MapAnimation.MapAnimation>();
    [global::ProtoBuf.ProtoMember(12, Name=@"animations", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapAnimation.MapAnimation> animations
    {
      get { return _animations; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapOpenPolicy")]
  public partial class MapOpenPolicy : global::ProtoBuf.IExtensible
  {
    public MapOpenPolicy() {}
    
    private readonly global::System.Collections.Generic.List<MapOpenPolicy.OpenType> _openTypes = new global::System.Collections.Generic.List<MapOpenPolicy.OpenType>();
    [global::ProtoBuf.ProtoMember(1, Name=@"openTypes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<MapOpenPolicy.OpenType> openTypes
    {
      get { return _openTypes; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _openValues = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"openValues", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> openValues
    {
      get { return _openValues; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"OpenType")]
    public enum OpenType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OT_NONE", Value=0)]
      OT_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OT_LEVEL", Value=1)]
      OT_LEVEL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OT_MISSON", Value=2)]
      OT_MISSON = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapEnterPolicy")]
  public partial class MapEnterPolicy : global::ProtoBuf.IExtensible
  {
    public MapEnterPolicy() {}
    
    private int _minPlayerLevel = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"minPlayerLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minPlayerLevel
    {
      get { return _minPlayerLevel; }
      set { _minPlayerLevel = value; }
    }
    private int _maxPlayerLevel = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"maxPlayerLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxPlayerLevel
    {
      get { return _maxPlayerLevel; }
      set { _maxPlayerLevel = value; }
    }
    private int _minTeamMember = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"minTeamMember", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minTeamMember
    {
      get { return _minTeamMember; }
      set { _minTeamMember = value; }
    }
    private int _maxTeamMember = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"maxTeamMember", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxTeamMember
    {
      get { return _maxTeamMember; }
      set { _maxTeamMember = value; }
    }
    private int _maxPlayerCount = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"maxPlayerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxPlayerCount
    {
      get { return _maxPlayerCount; }
      set { _maxPlayerCount = value; }
    }
    private readonly global::System.Collections.Generic.List<Item.Item> _consume = new global::System.Collections.Generic.List<Item.Item>();
    [global::ProtoBuf.ProtoMember(6, Name=@"consume", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Item.Item> consume
    {
      get { return _consume; }
    }
  
    private int _stopTeamBossID = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"stopTeamBossID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stopTeamBossID
    {
      get { return _stopTeamBossID; }
      set { _stopTeamBossID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapLimit")]
  public partial class MapLimit : global::ProtoBuf.IExtensible
  {
    public MapLimit() {}
    
    private bool _canRide = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"canRide", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool canRide
    {
      get { return _canRide; }
      set { _canRide = value; }
    }
    private bool _canKick = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"canKick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool canKick
    {
      get { return _canKick; }
      set { _canKick = value; }
    }
    private bool _canApplySummon = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"canApplySummon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool canApplySummon
    {
      get { return _canApplySummon; }
      set { _canApplySummon = value; }
    }
    private bool _canFormTream = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"canFormTream", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool canFormTream
    {
      get { return _canFormTream; }
      set { _canFormTream = value; }
    }
    private bool _canSkillTransmit = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"canSkillTransmit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool canSkillTransmit
    {
      get { return _canSkillTransmit; }
      set { _canSkillTransmit = value; }
    }
    private bool _canChangeRelation = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"canChangeRelation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool canChangeRelation
    {
      get { return _canChangeRelation; }
      set { _canChangeRelation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapAssistPolicy")]
  public partial class MapAssistPolicy : global::ProtoBuf.IExtensible
  {
    public MapAssistPolicy() {}
    
    private MapAssistPolicy.AssistType _type = MapAssistPolicy.AssistType.NONE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapAssistPolicy.AssistType.NONE)]
    public MapAssistPolicy.AssistType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _initCount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"initCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int initCount
    {
      get { return _initCount; }
      set { _initCount = value; }
    }
    private int _totalCount = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"totalCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalCount
    {
      get { return _totalCount; }
      set { _totalCount = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"AssistType")]
    public enum AssistType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=1)]
      NONE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELAY", Value=2)]
      DELAY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL_AT_ONCE", Value=3)]
      ALL_AT_ONCE = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapRelivePolicy")]
  public partial class MapRelivePolicy : global::ProtoBuf.IExtensible
  {
    public MapRelivePolicy() {}
    
    private int _reviveNum = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reviveNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reviveNum
    {
      get { return _reviveNum; }
      set { _reviveNum = value; }
    }
    private MapRelivePolicy.RevivePunish _revivePunish = MapRelivePolicy.RevivePunish.RP_NONE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"revivePunish", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapRelivePolicy.RevivePunish.RP_NONE)]
    public MapRelivePolicy.RevivePunish revivePunish
    {
      get { return _revivePunish; }
      set { _revivePunish = value; }
    }
    private int _reviveTimer = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reviveTimer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int reviveTimer
    {
      get { return _reviveTimer; }
      set { _reviveTimer = value; }
    }
    private int _punishValue = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"punishValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int punishValue
    {
      get { return _punishValue; }
      set { _punishValue = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RevivePunish")]
    public enum RevivePunish
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RP_NONE", Value=0)]
      RP_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RP_HP", Value=1)]
      RP_HP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RP_GOLD", Value=2)]
      RP_GOLD = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapClearPolicy")]
  public partial class MapClearPolicy : global::ProtoBuf.IExtensible
  {
    public MapClearPolicy() {}
    
    private readonly global::System.Collections.Generic.List<MapClearPolicy.OverCondition> _conditionTypes = new global::System.Collections.Generic.List<MapClearPolicy.OverCondition>();
    [global::ProtoBuf.ProtoMember(1, Name=@"conditionTypes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<MapClearPolicy.OverCondition> conditionTypes
    {
      get { return _conditionTypes; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _conditionValues = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"conditionValues", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> conditionValues
    {
      get { return _conditionValues; }
    }
  
    private int _dropID = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dropID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dropID
    {
      get { return _dropID; }
      set { _dropID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"OverCondition")]
    public enum OverCondition
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OC_MAP_EVENT", Value=0)]
      OC_MAP_EVENT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OC_KILL_BOSS", Value=1)]
      OC_KILL_BOSS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OC_COLLECT_Item", Value=2)]
      OC_COLLECT_Item = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OC_NPC_POSITION", Value=3)]
      OC_NPC_POSITION = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OC_ALIVETIME", Value=4)]
      OC_ALIVETIME = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OC_NPC_ALIVETIME", Value=5)]
      OC_NPC_ALIVETIME = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OC_POSITION", Value=6)]
      OC_POSITION = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OC_PREVENT_NPC_POSITION", Value=7)]
      OC_PREVENT_NPC_POSITION = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapEvaluatePolicy")]
  public partial class MapEvaluatePolicy : global::ProtoBuf.IExtensible
  {
    public MapEvaluatePolicy() {}
    
    private MapEvaluatePolicy.EvaluateType _evaluateType = MapEvaluatePolicy.EvaluateType.E_TIME;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"evaluateType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapEvaluatePolicy.EvaluateType.E_TIME)]
    public MapEvaluatePolicy.EvaluateType evaluateType
    {
      get { return _evaluateType; }
      set { _evaluateType = value; }
    }
    private int _rate1 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rate1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rate1
    {
      get { return _rate1; }
      set { _rate1 = value; }
    }
    private int _rate2 = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rate2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rate2
    {
      get { return _rate2; }
      set { _rate2 = value; }
    }
    private int _dropID = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dropID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dropID
    {
      get { return _dropID; }
      set { _dropID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"EvaluateType")]
    public enum EvaluateType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"E_TIME", Value=0)]
      E_TIME = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"E_KILLNPCNUM", Value=1)]
      E_KILLNPCNUM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"E_FRIENDDIENUM", Value=2)]
      E_FRIENDDIENUM = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapAwardShow")]
  public partial class MapAwardShow : global::ProtoBuf.IExtensible
  {
    public MapAwardShow() {}
    
    private readonly global::System.Collections.Generic.List<Item.Item> _Items = new global::System.Collections.Generic.List<Item.Item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Item.Items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Item.Item> Items
    {
      get { return _Items; }
    }
  
    private readonly global::System.Collections.Generic.List<Item.Item> _probability = new global::System.Collections.Generic.List<Item.Item>();
    [global::ProtoBuf.ProtoMember(2, Name=@"probability", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Item.Item> probability
    {
      get { return _probability; }
    }
  
    private string _awardDesc = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"awardDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string awardDesc
    {
      get { return _awardDesc; }
      set { _awardDesc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapResource")]
  public partial class MapResource : global::ProtoBuf.IExtensible
  {
    public MapResource() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private string _picture = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"picture", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string picture
    {
      get { return _picture; }
      set { _picture = value; }
    }
    private string _loading = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"loading", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string loading
    {
      get { return _loading; }
      set { _loading = value; }
    }
    private string _music = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"music", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string music
    {
      get { return _music; }
      set { _music = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapInfo")]
  public partial class MapInfo : global::ProtoBuf.IExtensible
  {
    public MapInfo() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private MapInfo.MapType _mapType = MapInfo.MapType.MAIN_CITY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mapType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapInfo.MapType.MAIN_CITY)]
    public MapInfo.MapType mapType
    {
      get { return _mapType; }
      set { _mapType = value; }
    }
    private int _unit = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"unit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int unit
    {
      get { return _unit; }
      set { _unit = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _desc = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private MapInfo.InstanceType _type = MapInfo.InstanceType.SINGLE;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapInfo.InstanceType.SINGLE)]
    public MapInfo.InstanceType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private MapResource _resource = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"resource", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapResource resource
    {
      get { return _resource; }
      set { _resource = value; }
    }
    private MapAwardShow _awardShow = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"awardShow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapAwardShow awardShow
    {
      get { return _awardShow; }
      set { _awardShow = value; }
    }
    private MapInfo.DifficultyType _difficultyType = MapInfo.DifficultyType.ORDINARY;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"difficultyType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapInfo.DifficultyType.ORDINARY)]
    public MapInfo.DifficultyType difficultyType
    {
      get { return _difficultyType; }
      set { _difficultyType = value; }
    }
    private int _recommendCapacity = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"recommendCapacity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int recommendCapacity
    {
      get { return _recommendCapacity; }
      set { _recommendCapacity = value; }
    }
    private MapOpenPolicy _mapOpenPolicy = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"mapOpenPolicy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapOpenPolicy mapOpenPolicy
    {
      get { return _mapOpenPolicy; }
      set { _mapOpenPolicy = value; }
    }
    private MapEnterPolicy _mapEnterPolicy = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"mapEnterPolicy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapEnterPolicy mapEnterPolicy
    {
      get { return _mapEnterPolicy; }
      set { _mapEnterPolicy = value; }
    }
    private MapLimit _mapLimit = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"mapLimit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapLimit mapLimit
    {
      get { return _mapLimit; }
      set { _mapLimit = value; }
    }
    private MapAssistPolicy _assistPolicy = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"assistPolicy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapAssistPolicy assistPolicy
    {
      get { return _assistPolicy; }
      set { _assistPolicy = value; }
    }
    private MapRelivePolicy _relivePolicy = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"relivePolicy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapRelivePolicy relivePolicy
    {
      get { return _relivePolicy; }
      set { _relivePolicy = value; }
    }
    private MapEvaluatePolicy _evaluatePolicy = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"evaluatePolicy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapEvaluatePolicy evaluatePolicy
    {
      get { return _evaluatePolicy; }
      set { _evaluatePolicy = value; }
    }
    private MapClearPolicy _clearPolicy = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"clearPolicy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapClearPolicy clearPolicy
    {
      get { return _clearPolicy; }
      set { _clearPolicy = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MapType")]
    public enum MapType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIN_CITY", Value=1)]
      MAIN_CITY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIELD_COMMON", Value=2)]
      FIELD_COMMON = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIELD_FACTION", Value=3)]
      FIELD_FACTION = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCHOOL", Value=4)]
      SCHOOL = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INSTANTCE", Value=5)]
      INSTANTCE = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"InstanceType")]
    public enum InstanceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SINGLE", Value=1)]
      SINGLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM", Value=2)]
      TEAM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FACTION", Value=3)]
      FACTION = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUP", Value=4)]
      GROUP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAMILY", Value=5)]
      FAMILY = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MENTORING", Value=6)]
      MENTORING = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOVE", Value=7)]
      LOVE = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DifficultyType")]
    public enum DifficultyType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORDINARY", Value=0)]
      ORDINARY = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ELITE", Value=1)]
      ELITE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EPIC", Value=2)]
      EPIC = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEGEND", Value=3)]
      LEGEND = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapActivityTime")]
  public partial class MapActivityTime : global::ProtoBuf.IExtensible
  {
    public MapActivityTime() {}
    
    private int _startTime = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private int _endTime = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapActivityNotice")]
  public partial class MapActivityNotice : global::ProtoBuf.IExtensible
  {
    public MapActivityNotice() {}
    
    private int _prepare = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"prepare", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int prepare
    {
      get { return _prepare; }
      set { _prepare = value; }
    }
    private int _start = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int start
    {
      get { return _start; }
      set { _start = value; }
    }
    private int _over = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"over", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int over
    {
      get { return _over; }
      set { _over = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapActivity")]
  public partial class MapActivity : global::ProtoBuf.IExtensible
  {
    public MapActivity() {}
    
    private int _mapId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private int _name = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<bool> _openDays = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(3, Name=@"openDays", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> openDays
    {
      get { return _openDays; }
    }
  
    private readonly global::System.Collections.Generic.List<MapActivityTime> _openTimes = new global::System.Collections.Generic.List<MapActivityTime>();
    [global::ProtoBuf.ProtoMember(4, Name=@"openTimes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapActivityTime> openTimes
    {
      get { return _openTimes; }
    }
  
    private int _openInterval = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"openInterval", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int openInterval
    {
      get { return _openInterval; }
      set { _openInterval = value; }
    }
    private int _prepareTime = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"prepareTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int prepareTime
    {
      get { return _prepareTime; }
      set { _prepareTime = value; }
    }
    private MapActivityNotice _notice = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"notice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapActivityNotice notice
    {
      get { return _notice; }
      set { _notice = value; }
    }
    private MapActivity.EnterPeriodLimit _peroidLimit = MapActivity.EnterPeriodLimit.NONE;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"peroidLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapActivity.EnterPeriodLimit.NONE)]
    public MapActivity.EnterPeriodLimit peroidLimit
    {
      get { return _peroidLimit; }
      set { _peroidLimit = value; }
    }
    private int _maxEnterCount = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"maxEnterCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxEnterCount
    {
      get { return _maxEnterCount; }
      set { _maxEnterCount = value; }
    }
    private int _maxBuyEnterCount = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"maxBuyEnterCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxBuyEnterCount
    {
      get { return _maxBuyEnterCount; }
      set { _maxBuyEnterCount = value; }
    }
    private int _enterBuyPrice = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"enterBuyPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int enterBuyPrice
    {
      get { return _enterBuyPrice; }
      set { _enterBuyPrice = value; }
    }
    private bool _enterIngoreCount = default(bool);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"enterIngoreCount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool enterIngoreCount
    {
      get { return _enterIngoreCount; }
      set { _enterIngoreCount = value; }
    }
    private bool _rewardIgnoreCount = default(bool);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"rewardIgnoreCount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool rewardIgnoreCount
    {
      get { return _rewardIgnoreCount; }
      set { _rewardIgnoreCount = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"EnterPeriodLimit")]
    public enum EnterPeriodLimit
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVERYDAY", Value=1)]
      EVERYDAY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVERYWEEK", Value=2)]
      EVERYWEEK = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVERYMONTH", Value=3)]
      EVERYMONTH = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllMaps")]
  public partial class AllMaps : global::ProtoBuf.IExtensible
  {
    public AllMaps() {}
    
    private readonly global::System.Collections.Generic.List<MapInfo> _maps = new global::System.Collections.Generic.List<MapInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"maps", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapInfo> maps
    {
      get { return _maps; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllMapActivities")]
  public partial class AllMapActivities : global::ProtoBuf.IExtensible
  {
    public AllMapActivities() {}
    
    private readonly global::System.Collections.Generic.List<MapActivity> _activities = new global::System.Collections.Generic.List<MapActivity>();
    [global::ProtoBuf.ProtoMember(1, Name=@"activities", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapActivity> activities
    {
      get { return _activities; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}