//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MovementAtt.proto
// Note: requires additional types generated from: Math.proto
using Math;

namespace MovementAtt
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MovementAtt")]
  public partial class MovementAtt : global::ProtoBuf.IExtensible
  {
    public MovementAtt() {}
    
    private Vector3f _position = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f position
    {
      get { return _position; }
      set { _position = value; }
    }
    private float _runSpeed = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"runSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float runSpeed
    {
      get { return _runSpeed; }
      set { _runSpeed = value; }
    }
    private Vector3f _rotation = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}