//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Physique.proto
// Note: requires additional types generated from: StringID.proto
namespace Physique
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipModel")]
  public partial class EquipModel : global::ProtoBuf.IExtensible
  {
    public EquipModel() {}
    
    private string _model = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"model", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string model
    {
      get { return _model; }
      set { _model = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Physique")]
  public partial class Physique : global::ProtoBuf.IExtensible
  {
    public Physique() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _physiqueBase = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"physiqueBase", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string physiqueBase
    {
      get { return _physiqueBase; }
      set { _physiqueBase = value; }
    }
    private string _animatorController = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"animatorController", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string animatorController
    {
      get { return _animatorController; }
      set { _animatorController = value; }
    }
    private string _face = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"face", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string face
    {
      get { return _face; }
      set { _face = value; }
    }
    private readonly global::System.Collections.Generic.List<EquipModel> _equips = new global::System.Collections.Generic.List<EquipModel>();
    [global::ProtoBuf.ProtoMember(5, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EquipModel> equips
    {
      get { return _equips; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllPhysiques")]
  public partial class AllPhysiques : global::ProtoBuf.IExtensible
  {
    public AllPhysiques() {}
    
    private readonly global::System.Collections.Generic.List<Physique> _physiques = new global::System.Collections.Generic.List<Physique>();
    [global::ProtoBuf.ProtoMember(1, Name=@"physiques", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Physique> physiques
    {
      get { return _physiques; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}