//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RandomName.proto
namespace RandomName
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RandomDescribe")]
  public partial class RandomDescribe : global::ProtoBuf.IExtensible
  {
    public RandomDescribe() {}
    
    private string _data = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RandomLastName")]
  public partial class RandomLastName : global::ProtoBuf.IExtensible
  {
    public RandomLastName() {}
    
    private string _data = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RandomNameMale")]
  public partial class RandomNameMale : global::ProtoBuf.IExtensible
  {
    public RandomNameMale() {}
    
    private string _data = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RandomNameFemale")]
  public partial class RandomNameFemale : global::ProtoBuf.IExtensible
  {
    public RandomNameFemale() {}
    
    private string _data = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllRandomName")]
  public partial class AllRandomName : global::ProtoBuf.IExtensible
  {
    public AllRandomName() {}
    
    private readonly global::System.Collections.Generic.List<RandomDescribe> _describes = new global::System.Collections.Generic.List<RandomDescribe>();
    [global::ProtoBuf.ProtoMember(1, Name=@"describes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RandomDescribe> describes
    {
      get { return _describes; }
    }
  
    private readonly global::System.Collections.Generic.List<RandomLastName> _lastNames = new global::System.Collections.Generic.List<RandomLastName>();
    [global::ProtoBuf.ProtoMember(2, Name=@"lastNames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RandomLastName> lastNames
    {
      get { return _lastNames; }
    }
  
    private readonly global::System.Collections.Generic.List<RandomNameMale> _nameMales = new global::System.Collections.Generic.List<RandomNameMale>();
    [global::ProtoBuf.ProtoMember(3, Name=@"nameMales", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RandomNameMale> nameMales
    {
      get { return _nameMales; }
    }
  
    private readonly global::System.Collections.Generic.List<RandomNameFemale> _nameFemales = new global::System.Collections.Generic.List<RandomNameFemale>();
    [global::ProtoBuf.ProtoMember(4, Name=@"nameFemales", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RandomNameFemale> nameFemales
    {
      get { return _nameFemales; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}