//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SystemNotify.proto
// Note: requires additional types generated from: StringID.proto
using StringID;

namespace SystemNotify
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SystemNotify")]
  public partial class SystemNotify : global::ProtoBuf.IExtensible
  {
    public SystemNotify() {}
    
    private SysError _sys = SysError.SYSTEM_ERROR;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sys", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(SysError.SYSTEM_ERROR)]
    public SysError sys
    {
      get { return _sys; }
      set { _sys = value; }
    }
    private int _code1 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"code1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int code1
    {
      get { return _code1; }
      set { _code1 = value; }
    }
    private string _info = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllSystemNotifys")]
  public partial class AllSystemNotifys : global::ProtoBuf.IExtensible
  {
    public AllSystemNotifys() {}
    
    private AllStringID _stringID = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stringID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AllStringID stringID
    {
      get { return _stringID; }
      set { _stringID = value; }
    }
    private readonly global::System.Collections.Generic.List<SystemNotify> _systemNotify = new global::System.Collections.Generic.List<SystemNotify>();
    [global::ProtoBuf.ProtoMember(2, Name=@"systemNotify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SystemNotify> systemNotify
    {
      get { return _systemNotify; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SysError")]
    public enum SysError
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYSTEM_ERROR", Value=0)]
      SYSTEM_ERROR = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYSTEM_BAG", Value=1)]
      SYSTEM_BAG = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SysErrorCode")]
    public enum SysErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_SERVER_EXCEPTION", Value=0)]
      SYS_SERVER_EXCEPTION = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_PARAM_NOT_FOUND", Value=1)]
      SYS_PARAM_NOT_FOUND = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_PARAM_ERROR", Value=2)]
      SYS_PARAM_ERROR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_TOKEN_ERROR", Value=3)]
      SYS_TOKEN_ERROR = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_NOT_FOUND_SERVER", Value=4)]
      SYS_NOT_FOUND_SERVER = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYS_MAP_ERROR", Value=5)]
      SYS_MAP_ERROR = 5
    }
  
}