//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: WordData.proto
namespace WordData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllWordData")]
  public partial class AllWordData : global::ProtoBuf.IExtensible
  {
    public AllWordData() {}
    
    private readonly global::System.Collections.Generic.List<WordData> _tlist = new global::System.Collections.Generic.List<WordData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<WordData> tlist
    {
      get { return _tlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WordData")]
  public partial class WordData : global::ProtoBuf.IExtensible
  {
    public WordData() {}
    
    private int _key = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int key
    {
      get { return _key; }
      set { _key = value; }
    }
    private string _stringValue = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stringValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stringValue
    {
      get { return _stringValue; }
      set { _stringValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WordMappingData")]
  public partial class WordMappingData : global::ProtoBuf.IExtensible
  {
    public WordMappingData() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _key = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private int _channel = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int channel
    {
      get { return _channel; }
      set { _channel = value; }
    }
    private ChannelTimeType _timeType = ChannelTimeType.REALTIME;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"timeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ChannelTimeType.REALTIME)]
    public ChannelTimeType timeType
    {
      get { return _timeType; }
      set { _timeType = value; }
    }
    private string _startTime = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private int _interDay = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"interDay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int interDay
    {
      get { return _interDay; }
      set { _interDay = value; }
    }
    private int _playCount = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"playCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playCount
    {
      get { return _playCount; }
      set { _playCount = value; }
    }
    private int _playDelta = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"playDelta", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playDelta
    {
      get { return _playDelta; }
      set { _playDelta = value; }
    }
    private int _chatChannel = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"chatChannel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chatChannel
    {
      get { return _chatChannel; }
      set { _chatChannel = value; }
    }
    private int _priority = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"priority", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int priority
    {
      get { return _priority; }
      set { _priority = value; }
    }
    private NoticeType _noticeType = NoticeType.NOTICE_START;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"noticeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(NoticeType.NOTICE_START)]
    public NoticeType noticeType
    {
      get { return _noticeType; }
      set { _noticeType = value; }
    }
    private int _replaceFlag = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"replaceFlag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int replaceFlag
    {
      get { return _replaceFlag; }
      set { _replaceFlag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllWordMappingDatas")]
  public partial class AllWordMappingDatas : global::ProtoBuf.IExtensible
  {
    public AllWordMappingDatas() {}
    
    private readonly global::System.Collections.Generic.List<WordMappingData> _datas = new global::System.Collections.Generic.List<WordMappingData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<WordMappingData> datas
    {
      get { return _datas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ChannelTimeType")]
    public enum ChannelTimeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REALTIME", Value=1)]
      REALTIME = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DOUBLE_MONTH_DAY", Value=2)]
      DOUBLE_MONTH_DAY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SINGLE_MONTH_DAY", Value=3)]
      SINGLE_MONTH_DAY = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAY", Value=4)]
      DAY = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVERY_DAY", Value=5)]
      EVERY_DAY = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"NoticeType")]
    public enum NoticeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTICE_START", Value=1)]
      NOTICE_START = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTICE_ALERT", Value=2)]
      NOTICE_ALERT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTICE_END", Value=3)]
      NOTICE_END = 3
    }
  
}