//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AIAtt.proto
namespace AIAtt
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AIAtt")]
  public partial class AIAtt : global::ProtoBuf.IExtensible
  {
    public AIAtt() {}
    
    private int _moveInterval = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"moveInterval", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int moveInterval
    {
      get { return _moveInterval; }
      set { _moveInterval = value; }
    }
    private float _moveRadius = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"moveRadius", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float moveRadius
    {
      get { return _moveRadius; }
      set { _moveRadius = value; }
    }
    private int _attackInterval = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"attackInterval", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attackInterval
    {
      get { return _attackInterval; }
      set { _attackInterval = value; }
    }
    private int _thinkInterval = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"thinkInterval", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int thinkInterval
    {
      get { return _thinkInterval; }
      set { _thinkInterval = value; }
    }
    private int _searchInterval = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"searchInterval", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int searchInterval
    {
      get { return _searchInterval; }
      set { _searchInterval = value; }
    }
    private float _searchRadius = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"searchRadius", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float searchRadius
    {
      get { return _searchRadius; }
      set { _searchRadius = value; }
    }
    private string _scriptName = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"scriptName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string scriptName
    {
      get { return _scriptName; }
      set { _scriptName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}