//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Bag.proto
// Note: requires additional types generated from: Item.proto
namespace Bag
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BagPage")]
  public partial class BagPage : global::ProtoBuf.IExtensible
  {
    public BagPage() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _gridopencount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gridopencount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gridopencount
    {
      get { return _gridopencount; }
      set { _gridopencount = value; }
    }
    private readonly global::System.Collections.Generic.List<Item.Item> _bagGridList = new global::System.Collections.Generic.List<Item.Item>();
    [global::ProtoBuf.ProtoMember(3, Name=@"bagGridList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Item.Item> bagGridList
    {
      get { return _bagGridList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BagPageGroup")]
  public partial class BagPageGroup : global::ProtoBuf.IExtensible
  {
    public BagPageGroup() {}
    
    private readonly global::System.Collections.Generic.List<BagPage> _bagPageList = new global::System.Collections.Generic.List<BagPage>();
    [global::ProtoBuf.ProtoMember(1, Name=@"bagPageList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BagPage> bagPageList
    {
      get { return _bagPageList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Bag")]
  public partial class Bag : global::ProtoBuf.IExtensible
  {
    public Bag() {}
    
    private readonly global::System.Collections.Generic.List<BagPageGroup> _pageGroupList = new global::System.Collections.Generic.List<BagPageGroup>();
    [global::ProtoBuf.ProtoMember(1, Name=@"pageGroupList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BagPageGroup> pageGroupList
    {
      get { return _pageGroupList; }
    }
  
    private int _ingotCount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ingotCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ingotCount
    {
      get { return _ingotCount; }
      set { _ingotCount = value; }
    }
    private int _goldCount = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"goldCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int goldCount
    {
      get { return _goldCount; }
      set { _goldCount = value; }
    }
    private int _silverCount = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"silverCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int silverCount
    {
      get { return _silverCount; }
      set { _silverCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"BagType")]
    public enum BagType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BACKPACK", Value=0)]
      BACKPACK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WAREHOUSE", Value=1)]
      WAREHOUSE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEMP", Value=2)]
      TEMP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FASHION", Value=3)]
      FASHION = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIP", Value=4)]
      EQUIP = 4
    }
  
}