//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Dialog.proto
// Note: requires additional types generated from: StringID.proto
using StringID;

namespace Dialog
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DialogString")]
  public partial class DialogString : global::ProtoBuf.IExtensible
  {
    public DialogString() {}
    
    private string _data = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DialogData")]
  public partial class DialogData : global::ProtoBuf.IExtensible
  {
    public DialogData() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _dialogID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dialogID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dialogID
    {
      get { return _dialogID; }
      set { _dialogID = value; }
    }
    private int _dialogType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dialogType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dialogType
    {
      get { return _dialogType; }
      set { _dialogType = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private readonly global::System.Collections.Generic.List<DialogString> _content = new global::System.Collections.Generic.List<DialogString>();
    [global::ProtoBuf.ProtoMember(5, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DialogString> content
    {
      get { return _content; }
    }
  
    private float _cameraType = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"cameraType", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float cameraType
    {
      get { return _cameraType; }
      set { _cameraType = value; }
    }
    private int _topNpcID = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"topNpcID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int topNpcID
    {
      get { return _topNpcID; }
      set { _topNpcID = value; }
    }
    private int _modelNpcID = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"modelNpcID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int modelNpcID
    {
      get { return _modelNpcID; }
      set { _modelNpcID = value; }
    }
    private bool _modelLeft = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"modelLeft", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool modelLeft
    {
      get { return _modelLeft; }
      set { _modelLeft = value; }
    }
    private string _headIconName = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"headIconName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headIconName
    {
      get { return _headIconName; }
      set { _headIconName = value; }
    }
    private bool _headLeft = default(bool);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"headLeft", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool headLeft
    {
      get { return _headLeft; }
      set { _headLeft = value; }
    }
    private DialogData.HEAD_POS_TYPE _headPosType = DialogData.HEAD_POS_TYPE.LEFT;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"headPosType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(DialogData.HEAD_POS_TYPE.LEFT)]
    public DialogData.HEAD_POS_TYPE headPosType
    {
      get { return _headPosType; }
      set { _headPosType = value; }
    }
    private string _npcAnimationName = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"npcAnimationName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string npcAnimationName
    {
      get { return _npcAnimationName; }
      set { _npcAnimationName = value; }
    }
    private string _storyID = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"storyID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string storyID
    {
      get { return _storyID; }
      set { _storyID = value; }
    }
    private readonly global::System.Collections.Generic.List<DialogString> _audio = new global::System.Collections.Generic.List<DialogString>();
    [global::ProtoBuf.ProtoMember(16, Name=@"audio", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DialogString> audio
    {
      get { return _audio; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _disAppearTime = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(17, Name=@"disAppearTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> disAppearTime
    {
      get { return _disAppearTime; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DialogType")]
    public enum DialogType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NPC", Value=1)]
      NPC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOP", Value=2)]
      TOP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMON", Value=3)]
      COMMON = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MODEL", Value=4)]
      MODEL = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TIP_WITH_HEAD", Value=5)]
      TIP_WITH_HEAD = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TIP_NO_HEAD", Value=6)]
      TIP_NO_HEAD = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STORY", Value=7)]
      STORY = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"HEAD_POS_TYPE")]
    public enum HEAD_POS_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEFT", Value=1)]
      LEFT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MIDDLE", Value=2)]
      MIDDLE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RIGHT", Value=3)]
      RIGHT = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllDialogDatas")]
  public partial class AllDialogDatas : global::ProtoBuf.IExtensible
  {
    public AllDialogDatas() {}
    
    private readonly global::System.Collections.Generic.List<DialogData> _datas = new global::System.Collections.Generic.List<DialogData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DialogData> datas
    {
      get { return _datas; }
    }
  
    private AllStringID _stringID = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stringID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AllStringID stringID
    {
      get { return _stringID; }
      set { _stringID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}