//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EquipmentAtt.proto
namespace EquipmentAtt
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipmentAsset")]
  public partial class EquipmentAsset : global::ProtoBuf.IExtensible
  {
    public EquipmentAsset() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _resID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int resID
    {
      get { return _resID; }
      set { _resID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _propertyBaseID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"propertyBaseID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> propertyBaseID
    {
      get { return _propertyBaseID; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _propertyBaseValue = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"propertyBaseValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> propertyBaseValue
    {
      get { return _propertyBaseValue; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _propertyAttachID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"propertyAttachID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> propertyAttachID
    {
      get { return _propertyAttachID; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _propertyAttachValue = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"propertyAttachValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> propertyAttachValue
    {
      get { return _propertyAttachValue; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _propertyAttachRatioID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"propertyAttachRatioID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> propertyAttachRatioID
    {
      get { return _propertyAttachRatioID; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _propertyAttachRatio = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(8, Name=@"propertyAttachRatio", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> propertyAttachRatio
    {
      get { return _propertyAttachRatio; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _propertySpecialIntID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"propertySpecialIntID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> propertySpecialIntID
    {
      get { return _propertySpecialIntID; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _propertySpecialIntValue = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"propertySpecialIntValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> propertySpecialIntValue
    {
      get { return _propertySpecialIntValue; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _propertySpecialFloatID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"propertySpecialFloatID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> propertySpecialFloatID
    {
      get { return _propertySpecialFloatID; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _propertySpecialFloatValue = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(12, Name=@"propertySpecialFloatValue", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> propertySpecialFloatValue
    {
      get { return _propertySpecialFloatValue; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipmentStrategy")]
  public partial class EquipmentStrategy : global::ProtoBuf.IExtensible
  {
    public EquipmentStrategy() {}
    
    private readonly global::System.Collections.Generic.List<int> _equips = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> equips
    {
      get { return _equips; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipmentAtt")]
  public partial class EquipmentAtt : global::ProtoBuf.IExtensible
  {
    public EquipmentAtt() {}
    
    private readonly global::System.Collections.Generic.List<EquipmentStrategy> _equipStrategy = new global::System.Collections.Generic.List<EquipmentStrategy>();
    [global::ProtoBuf.ProtoMember(1, Name=@"equipStrategy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EquipmentStrategy> equipStrategy
    {
      get { return _equipStrategy; }
    }
  
    private int _equipStrategyActive = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"equipStrategyActive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipStrategyActive
    {
      get { return _equipStrategyActive; }
      set { _equipStrategyActive = value; }
    }
    private readonly global::System.Collections.Generic.List<EquipmentAsset> _equipAssets = new global::System.Collections.Generic.List<EquipmentAsset>();
    [global::ProtoBuf.ProtoMember(3, Name=@"equipAssets", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EquipmentAsset> equipAssets
    {
      get { return _equipAssets; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}