//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FightAtt.proto
// Note: requires additional types generated from: StringID.proto
using StringID;

namespace FightAtt
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillAsset")]
  public partial class SkillAsset : global::ProtoBuf.IExtensible
  {
    public SkillAsset() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Faction")]
  public partial class Faction : global::ProtoBuf.IExtensible
  {
    public Faction() {}
    
    private readonly global::System.Collections.Generic.List<int> _factionGroup = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"factionGroup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> factionGroup
    {
      get { return _factionGroup; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"FactionType")]
    public enum FactionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM", Value=0)]
      TEAM = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAMILY", Value=1)]
      FAMILY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCHOOL", Value=2)]
      SCHOOL = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"FactionRelation")]
    public enum FactionRelation
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GREEN", Value=0)]
      GREEN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"YELLOW", Value=1)]
      YELLOW = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RED", Value=2)]
      RED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ONEPHASE", Value=3)]
      ONEPHASE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVINCIBLE", Value=4)]
      INVINCIBLE = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightAtt")]
  public partial class FightAtt : global::ProtoBuf.IExtensible
  {
    public FightAtt() {}
    
    private PropertyAtt _property = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"property", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PropertyAtt property
    {
      get { return _property; }
      set { _property = value; }
    }
    private readonly global::System.Collections.Generic.List<SkillAsset> _skills = new global::System.Collections.Generic.List<SkillAsset>();
    [global::ProtoBuf.ProtoMember(2, Name=@"skills", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SkillAsset> skills
    {
      get { return _skills; }
    }
  
    private Faction _faction = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"faction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Faction faction
    {
      get { return _faction; }
      set { _faction = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PropertyAtt")]
  public partial class PropertyAtt : global::ProtoBuf.IExtensible
  {
    public PropertyAtt() {}
    
    private int _hp = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _mana = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mana", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mana
    {
      get { return _mana; }
      set { _mana = value; }
    }
    private int _anger = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"anger", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int anger
    {
      get { return _anger; }
      set { _anger = value; }
    }
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _onePropertyBasic = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"onePropertyBasic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> onePropertyBasic
    {
      get { return _onePropertyBasic; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _onePropertyRatio = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(6, Name=@"onePropertyRatio", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> onePropertyRatio
    {
      get { return _onePropertyRatio; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _onePropertyAttach = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"onePropertyAttach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> onePropertyAttach
    {
      get { return _onePropertyAttach; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _twoPropertyBasic = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"twoPropertyBasic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> twoPropertyBasic
    {
      get { return _twoPropertyBasic; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _twoPropertyRatio = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(9, Name=@"twoPropertyRatio", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> twoPropertyRatio
    {
      get { return _twoPropertyRatio; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _twoPropertyAttach = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"twoPropertyAttach", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> twoPropertyAttach
    {
      get { return _twoPropertyAttach; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _twoPropertyGloblRatio = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(11, Name=@"twoPropertyGloblRatio", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> twoPropertyGloblRatio
    {
      get { return _twoPropertyGloblRatio; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _special_int_list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"special_int_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> special_int_list
    {
      get { return _special_int_list; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _special_float_list = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(13, Name=@"special_float_list", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> special_float_list
    {
      get { return _special_float_list; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _onePropertyInit = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(14, Name=@"onePropertyInit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> onePropertyInit
    {
      get { return _onePropertyInit; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _onePropertyGrowUp = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(15, Name=@"onePropertyGrowUp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> onePropertyGrowUp
    {
      get { return _onePropertyGrowUp; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"OneProperty")]
    public enum OneProperty
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PHYSIQUE", Value=0)]
      PHYSIQUE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE", Value=1)]
      FORCE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AGILE", Value=2)]
      AGILE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEFTL", Value=3)]
      DEFTL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INTELLECT", Value=4)]
      INTELLECT = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TwoProperty")]
    public enum TwoProperty
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"HP", Value=0)]
      HP = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PHYSICSATT", Value=1)]
      PHYSICSATT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PHYSICSDEF", Value=2)]
      PHYSICSDEF = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAGICATT", Value=3)]
      MAGICATT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAGICDEF", Value=4)]
      MAGICDEF = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HIT", Value=5)]
      HIT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DODGE", Value=6)]
      DODGE = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLDATT", Value=7)]
      GOLDATT = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WOODATT", Value=8)]
      WOODATT = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WATERATT", Value=9)]
      WATERATT = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIREATT", Value=10)]
      FIREATT = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOILATT", Value=11)]
      SOILATT = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLDDEF", Value=12)]
      GOLDDEF = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WOODDEF", Value=13)]
      WOODDEF = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WATERDEF", Value=14)]
      WATERDEF = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIREDEF", Value=15)]
      FIREDEF = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOILDEF", Value=16)]
      SOILDEF = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IGNOREDODGE", Value=17)]
      IGNOREDODGE = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CRIT", Value=18)]
      CRIT = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CRITRES", Value=19)]
      CRITRES = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CRITHURT", Value=20)]
      CRITHURT = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CRITEXE", Value=21)]
      CRITEXE = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HPRECOVER", Value=22)]
      HPRECOVER = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MP", Value=23)]
      MP = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MPRECOVER", Value=24)]
      MPRECOVER = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ANGER_MAX", Value=25)]
      ANGER_MAX = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ANGER_INIT", Value=26)]
      ANGER_INIT = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTACK", Value=27)]
      ATTACK = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEFEND", Value=28)]
      DEFEND = 28
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SpecialInt")]
    public enum SpecialInt
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADDED_HURT", Value=0)]
      ADDED_HURT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL_ONELV", Value=1)]
      ALL_ONELV = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FL_ATTACK", Value=2)]
      FL_ATTACK = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FL_DEFEND", Value=3)]
      FL_DEFEND = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TREATMENT_ENHANCE", Value=4)]
      TREATMENT_ENHANCE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TENACITY", Value=5)]
      TENACITY = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SpecialFloat")]
    public enum SpecialFloat
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVE_SPEED", Value=0)]
      MOVE_SPEED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTACK_SPEED", Value=1)]
      ATTACK_SPEED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DRAWHP", Value=2)]
      DRAWHP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REBOUND_HURT", Value=3)]
      REBOUND_HURT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTACH_HITRATE", Value=4)]
      ATTACH_HITRATE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTACH_CRITRATE", Value=5)]
      ATTACH_CRITRATE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTACH_CRITMULTIPLE", Value=6)]
      ATTACH_CRITMULTIPLE = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD_MISS_HURT", Value=7)]
      GOLD_MISS_HURT = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WOOD_MISS_HURT", Value=8)]
      WOOD_MISS_HURT = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WATER_MISS_HURT", Value=9)]
      WATER_MISS_HURT = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIRE_MISS_HURT", Value=10)]
      FIRE_MISS_HURT = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOIL_MISS_HURT", Value=11)]
      SOIL_MISS_HURT = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD_ADD_HURT", Value=12)]
      GOLD_ADD_HURT = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WOOD_ADD_HURT", Value=13)]
      WOOD_ADD_HURT = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WATER_ADD_HURT", Value=14)]
      WATER_ADD_HURT = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIRE_ADD_HURT", Value=15)]
      FIRE_ADD_HURT = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOIL_ADD_HURT", Value=16)]
      SOIL_ADD_HURT = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TREATMENT_ENHANCE_RATIO", Value=17)]
      TREATMENT_ENHANCE_RATIO = 17
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PropertyMapping")]
  public partial class PropertyMapping : global::ProtoBuf.IExtensible
  {
    public PropertyMapping() {}
    
    private int _pid = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pid
    {
      get { return _pid; }
      set { _pid = value; }
    }
    private int _oneid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"oneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int oneid
    {
      get { return _oneid; }
      set { _oneid = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _twoids = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"twoids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> twoids
    {
      get { return _twoids; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _twovalues = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"twovalues", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> twovalues
    {
      get { return _twovalues; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllPropertyMapping")]
  public partial class AllPropertyMapping : global::ProtoBuf.IExtensible
  {
    public AllPropertyMapping() {}
    
    private readonly global::System.Collections.Generic.List<PropertyMapping> _maps = new global::System.Collections.Generic.List<PropertyMapping>();
    [global::ProtoBuf.ProtoMember(1, Name=@"maps", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PropertyMapping> maps
    {
      get { return _maps; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllPropertyAtts")]
  public partial class AllPropertyAtts : global::ProtoBuf.IExtensible
  {
    public AllPropertyAtts() {}
    
    private readonly global::System.Collections.Generic.List<PropertyAtt> _atts = new global::System.Collections.Generic.List<PropertyAtt>();
    [global::ProtoBuf.ProtoMember(1, Name=@"atts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PropertyAtt> atts
    {
      get { return _atts; }
    }
  
    private AllStringID _stringID = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stringID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AllStringID stringID
    {
      get { return _stringID; }
      set { _stringID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}