//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Item.proto
// Note: requires additional types generated from: StringID.proto
using StringID;

namespace Item
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item")]
  public partial class Item : global::ProtoBuf.IExtensible
  {
    public Item() {}
    
    private Item.ItemType _type = Item.ItemType.GOODS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Item.ItemType.GOODS)]
    public Item.ItemType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _count = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private bool _binded = (bool)false;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"binded", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool binded
    {
      get { return _binded; }
      set { _binded = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ItemType")]
    public enum ItemType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOODS", Value=1)]
      GOODS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIPMENT", Value=2)]
      EQUIPMENT = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemInfo")]
  public partial class ItemInfo : global::ProtoBuf.IExtensible
  {
    public ItemInfo() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private ItemInfo.ItemInfoType _itemInfoType = ItemInfo.ItemInfoType.COMMON;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"itemInfoType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ItemInfo.ItemInfoType.COMMON)]
    public ItemInfo.ItemInfoType itemInfoType
    {
      get { return _itemInfoType; }
      set { _itemInfoType = value; }
    }
    private int _childType = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"childType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int childType
    {
      get { return _childType; }
      set { _childType = value; }
    }
    private int _sort = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sort
    {
      get { return _sort; }
      set { _sort = value; }
    }
    private string _typedesc = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"typedesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string typedesc
    {
      get { return _typedesc; }
      set { _typedesc = value; }
    }
    private string _clientdesc = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"clientdesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clientdesc
    {
      get { return _clientdesc; }
      set { _clientdesc = value; }
    }
    private string _coredesc = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"coredesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string coredesc
    {
      get { return _coredesc; }
      set { _coredesc = value; }
    }
    private string _fundesc = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"fundesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fundesc
    {
      get { return _fundesc; }
      set { _fundesc = value; }
    }
    private string _icon_1 = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"icon_1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon_1
    {
      get { return _icon_1; }
      set { _icon_1 = value; }
    }
    private string _icon_2 = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"icon_2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon_2
    {
      get { return _icon_2; }
      set { _icon_2 = value; }
    }
    private ItemInfo.ItemBindType _bindType = ItemInfo.ItemBindType.NOT_BIND;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"bindType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ItemInfo.ItemBindType.NOT_BIND)]
    public ItemInfo.ItemBindType bindType
    {
      get { return _bindType; }
      set { _bindType = value; }
    }
    private int _useLevelDown = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"useLevelDown", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int useLevelDown
    {
      get { return _useLevelDown; }
      set { _useLevelDown = value; }
    }
    private int _maxCount = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"maxCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxCount
    {
      get { return _maxCount; }
      set { _maxCount = value; }
    }
    private int _maxSuperPosition = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"maxSuperPosition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxSuperPosition
    {
      get { return _maxSuperPosition; }
      set { _maxSuperPosition = value; }
    }
    private string _expiryDate = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"expiryDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string expiryDate
    {
      get { return _expiryDate; }
      set { _expiryDate = value; }
    }
    private ItemInfo.ItemOfftakeCoin _offtakeCoin = ItemInfo.ItemOfftakeCoin.INGOT;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"offtakeCoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ItemInfo.ItemOfftakeCoin.INGOT)]
    public ItemInfo.ItemOfftakeCoin offtakeCoin
    {
      get { return _offtakeCoin; }
      set { _offtakeCoin = value; }
    }
    private int _offtakeCoinCount = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"offtakeCoinCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int offtakeCoinCount
    {
      get { return _offtakeCoinCount; }
      set { _offtakeCoinCount = value; }
    }
    private bool _share = default(bool);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"share", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool share
    {
      get { return _share; }
      set { _share = value; }
    }
    private bool _autouse = default(bool);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"autouse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool autouse
    {
      get { return _autouse; }
      set { _autouse = value; }
    }
    private bool _sellShop = default(bool);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"sellShop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool sellShop
    {
      get { return _sellShop; }
      set { _sellShop = value; }
    }
    private bool _wareHouse = default(bool);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"wareHouse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool wareHouse
    {
      get { return _wareHouse; }
      set { _wareHouse = value; }
    }
    private bool _pitch = default(bool);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"pitch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool pitch
    {
      get { return _pitch; }
      set { _pitch = value; }
    }
    private int _maxUseCount = default(int);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"maxUseCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxUseCount
    {
      get { return _maxUseCount; }
      set { _maxUseCount = value; }
    }
    private ItemInfo.ItemUseProfession _useProfession = ItemInfo.ItemUseProfession.NOT_PROFESSSION;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"useProfession", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ItemInfo.ItemUseProfession.NOT_PROFESSSION)]
    public ItemInfo.ItemUseProfession useProfession
    {
      get { return _useProfession; }
      set { _useProfession = value; }
    }
    private ItemInfo.ItemUseSex _useSex = ItemInfo.ItemUseSex.NOT_SEX;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"useSex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ItemInfo.ItemUseSex.NOT_SEX)]
    public ItemInfo.ItemUseSex useSex
    {
      get { return _useSex; }
      set { _useSex = value; }
    }
    private ItemInfo.ItemUseLimit _useLimit = ItemInfo.ItemUseLimit.NOT_USE;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"useLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ItemInfo.ItemUseLimit.NOT_USE)]
    public ItemInfo.ItemUseLimit useLimit
    {
      get { return _useLimit; }
      set { _useLimit = value; }
    }
    private int _limitParam1 = default(int);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"limitParam1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int limitParam1
    {
      get { return _limitParam1; }
      set { _limitParam1 = value; }
    }
    private int _limitParam2 = default(int);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"limitParam2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int limitParam2
    {
      get { return _limitParam2; }
      set { _limitParam2 = value; }
    }
    private ItemInfo.ItemUseFun _useFun = ItemInfo.ItemUseFun.NOT_FUN;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"useFun", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ItemInfo.ItemUseFun.NOT_FUN)]
    public ItemInfo.ItemUseFun useFun
    {
      get { return _useFun; }
      set { _useFun = value; }
    }
    private string _useFunParam1 = "";
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"useFunParam1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string useFunParam1
    {
      get { return _useFunParam1; }
      set { _useFunParam1 = value; }
    }
    private string _useFunParam2 = "";
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"useFunParam2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string useFunParam2
    {
      get { return _useFunParam2; }
      set { _useFunParam2 = value; }
    }
    private string _useFunParam3 = "";
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"useFunParam3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string useFunParam3
    {
      get { return _useFunParam3; }
      set { _useFunParam3 = value; }
    }
    private int _dropOutId = default(int);
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"dropOutId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dropOutId
    {
      get { return _dropOutId; }
      set { _dropOutId = value; }
    }
    private ItemInfo.ItemInvalidFun _itemInvalidFun = ItemInfo.ItemInvalidFun.USE_CLEAR;
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"itemInvalidFun", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ItemInfo.ItemInvalidFun.USE_CLEAR)]
    public ItemInfo.ItemInvalidFun itemInvalidFun
    {
      get { return _itemInvalidFun; }
      set { _itemInvalidFun = value; }
    }
    private ItemInfo.ItemInvalidTimeUnit _itemInvalidTimeUnit = ItemInfo.ItemInvalidTimeUnit.MINUTE;
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"itemInvalidTimeUnit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ItemInfo.ItemInvalidTimeUnit.MINUTE)]
    public ItemInfo.ItemInvalidTimeUnit itemInvalidTimeUnit
    {
      get { return _itemInvalidTimeUnit; }
      set { _itemInvalidTimeUnit = value; }
    }
    private int _itemInvalidTimeData = default(int);
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"itemInvalidTimeData", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemInvalidTimeData
    {
      get { return _itemInvalidTimeData; }
      set { _itemInvalidTimeData = value; }
    }
    private int _useLevelUp = default(int);
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"useLevelUp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int useLevelUp
    {
      get { return _useLevelUp; }
      set { _useLevelUp = value; }
    }
    private ItemInfo.ItemQuality _quality = ItemInfo.ItemQuality.WHIITE;
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ItemInfo.ItemQuality.WHIITE)]
    public ItemInfo.ItemQuality quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private ItemInfo.DropNoticeChannel _dropNoticeChannel = ItemInfo.DropNoticeChannel.NOTICE_NONE;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"dropNoticeChannel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ItemInfo.DropNoticeChannel.NOTICE_NONE)]
    public ItemInfo.DropNoticeChannel dropNoticeChannel
    {
      get { return _dropNoticeChannel; }
      set { _dropNoticeChannel = value; }
    }
    private int _dropNoticeKey = default(int);
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"dropNoticeKey", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dropNoticeKey
    {
      get { return _dropNoticeKey; }
      set { _dropNoticeKey = value; }
    }
    private int _supplementID = default(int);
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"supplementID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int supplementID
    {
      get { return _supplementID; }
      set { _supplementID = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ItemInfoType")]
    public enum ItemInfoType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMON", Value=0)]
      COMMON = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUIP", Value=1)]
      EQUIP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GEMSTONE", Value=2)]
      GEMSTONE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COIN", Value=3)]
      COIN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TASK", Value=4)]
      TASK = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemChildType_COMMON")]
    public enum ItemChildType_COMMON
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GIFT", Value=0)]
      GIFT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DRUGS", Value=1)]
      DRUGS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MATERIAL", Value=2)]
      MATERIAL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUN", Value=3)]
      FUN = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemChildType_EQUIP")]
    public enum ItemChildType_EQUIP
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WEAPON", Value=0)]
      WEAPON = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEAD", Value=1)]
      HEAD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLOTH", Value=2)]
      CLOTH = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CUFF", Value=3)]
      CUFF = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BELT", Value=4)]
      BELT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOE", Value=5)]
      SHOE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"JADE", Value=6)]
      JADE = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NECKLACE", Value=7)]
      NECKLACE = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RING", Value=8)]
      RING = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BRACELET", Value=9)]
      BRACELET = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLOAK", Value=10)]
      CLOAK = 10
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemBindType")]
    public enum ItemBindType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_BIND", Value=0)]
      NOT_BIND = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOREVER", Value=1)]
      FOREVER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONDITION", Value=2)]
      CONDITION = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemQuality")]
    public enum ItemQuality
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WHIITE", Value=0)]
      WHIITE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GREEN", Value=1)]
      GREEN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLUE", Value=2)]
      BLUE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PURPLE", Value=3)]
      PURPLE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ORANGE", Value=4)]
      ORANGE = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemOfftakeCoin")]
    public enum ItemOfftakeCoin
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INGOT", Value=0)]
      INGOT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD", Value=1)]
      GOLD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SILVER", Value=2)]
      SILVER = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemUseProfession")]
    public enum ItemUseProfession
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_PROFESSSION", Value=0)]
      NOT_PROFESSSION = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLF", Value=1)]
      CLF = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GNJ", Value=2)]
      GNJ = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HB", Value=3)]
      HB = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SLJ", Value=4)]
      SLJ = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SJY", Value=5)]
      SJY = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemUseSex")]
    public enum ItemUseSex
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_SEX", Value=0)]
      NOT_SEX = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAN", Value=1)]
      MAN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WOMAN", Value=2)]
      WOMAN = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemUseLimit")]
    public enum ItemUseLimit
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_USE", Value=0)]
      NOT_USE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE", Value=1)]
      BATTLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAP", Value=2)]
      MAP = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemUseFun")]
    public enum ItemUseFun
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_FUN", Value=0)]
      NOT_FUN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADDHP", Value=1)]
      ADDHP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADDMP", Value=2)]
      ADDMP = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemInvalidFun")]
    public enum ItemInvalidFun
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"USE_CLEAR", Value=0)]
      USE_CLEAR = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AUTO_CLEAR", Value=1)]
      AUTO_CLEAR = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ItemInvalidTimeUnit")]
    public enum ItemInvalidTimeUnit
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MINUTE", Value=0)]
      MINUTE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAY", Value=1)]
      DAY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WEEK", Value=2)]
      WEEK = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MONTH", Value=3)]
      MONTH = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DropNoticeChannel")]
    public enum DropNoticeChannel
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTICE_NONE", Value=0)]
      NOTICE_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTICE_ALL", Value=1)]
      NOTICE_ALL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTICE_FAMILY", Value=2)]
      NOTICE_FAMILY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTICE_FRIEND", Value=3)]
      NOTICE_FRIEND = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOTICE_ALL_FAMILY_FRIEND", Value=4)]
      NOTICE_ALL_FAMILY_FRIEND = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllItemInfos")]
  public partial class AllItemInfos : global::ProtoBuf.IExtensible
  {
    public AllItemInfos() {}
    
    private AllStringID _stringID = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stringID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AllStringID stringID
    {
      get { return _stringID; }
      set { _stringID = value; }
    }
    private readonly global::System.Collections.Generic.List<ItemInfo> _iteminfos = new global::System.Collections.Generic.List<ItemInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"iteminfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ItemInfo> iteminfos
    {
      get { return _iteminfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}