//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MapAnimation.proto
// Note: requires additional types generated from: Math.proto
using Math;

namespace MapAnimation
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AnimationFrameActionValue")]
  public partial class AnimationFrameActionValue : global::ProtoBuf.IExtensible
  {
    public AnimationFrameActionValue() {}
    
    private Vector3f _vectorValue = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"vectorValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f vectorValue
    {
      get { return _vectorValue; }
      set { _vectorValue = value; }
    }
    private string _strValue = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"strValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strValue
    {
      get { return _strValue; }
      set { _strValue = value; }
    }
    private int _intValue = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"intValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int intValue
    {
      get { return _intValue; }
      set { _intValue = value; }
    }
    private float _floatValue = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"floatValue", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float floatValue
    {
      get { return _floatValue; }
      set { _floatValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AnimationFrameAction")]
  public partial class AnimationFrameAction : global::ProtoBuf.IExtensible
  {
    public AnimationFrameAction() {}
    
    private AnimationFrameAction.ActionType _actionType = AnimationFrameAction.ActionType.NONE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"actionType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(AnimationFrameAction.ActionType.NONE)]
    public AnimationFrameAction.ActionType actionType
    {
      get { return _actionType; }
      set { _actionType = value; }
    }
    private readonly global::System.Collections.Generic.List<AnimationFrameActionValue> _args = new global::System.Collections.Generic.List<AnimationFrameActionValue>();
    [global::ProtoBuf.ProtoMember(2, Name=@"args", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AnimationFrameActionValue> args
    {
      get { return _args; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ActionType")]
    public enum ActionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAY_ACTION", Value=4)]
      PLAY_ACTION = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STOP_ACTION", Value=5)]
      STOP_ACTION = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOW_EFFECT", Value=6)]
      SHOW_EFFECT = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HIDE_EFFECT", Value=7)]
      HIDE_EFFECT = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapAnimationFrame")]
  public partial class MapAnimationFrame : global::ProtoBuf.IExtensible
  {
    public MapAnimationFrame() {}
    
    private int _duration = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private readonly global::System.Collections.Generic.List<AnimationFrameAction> _actions = new global::System.Collections.Generic.List<AnimationFrameAction>();
    [global::ProtoBuf.ProtoMember(2, Name=@"actions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AnimationFrameAction> actions
    {
      get { return _actions; }
    }
  
    private MapAnimationFrame.RelativeType _positionType = MapAnimationFrame.RelativeType.ABSOLUTE;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"positionType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapAnimationFrame.RelativeType.ABSOLUTE)]
    public MapAnimationFrame.RelativeType positionType
    {
      get { return _positionType; }
      set { _positionType = value; }
    }
    private Vector3f _position = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f position
    {
      get { return _position; }
      set { _position = value; }
    }
    private MapAnimationFrame.RelativeType _rotationType = MapAnimationFrame.RelativeType.ABSOLUTE;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rotationType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapAnimationFrame.RelativeType.ABSOLUTE)]
    public MapAnimationFrame.RelativeType rotationType
    {
      get { return _rotationType; }
      set { _rotationType = value; }
    }
    private Vector3f _rotation = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private MapAnimationFrame.RelativeType _scaleType = MapAnimationFrame.RelativeType.ABSOLUTE;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"scaleType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapAnimationFrame.RelativeType.ABSOLUTE)]
    public MapAnimationFrame.RelativeType scaleType
    {
      get { return _scaleType; }
      set { _scaleType = value; }
    }
    private Vector3f _scale = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RelativeType")]
    public enum RelativeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ABSOLUTE", Value=0)]
      ABSOLUTE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RELATIVE", Value=1)]
      RELATIVE = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapAnimation")]
  public partial class MapAnimation : global::ProtoBuf.IExtensible
  {
    public MapAnimation() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _duration = (int)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int duration
    {
      get { return _duration; }
      set { _duration = value; }
    }
    private readonly global::System.Collections.Generic.List<MapAnimationFrame> _frames = new global::System.Collections.Generic.List<MapAnimationFrame>();
    [global::ProtoBuf.ProtoMember(4, Name=@"frames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapAnimationFrame> frames
    {
      get { return _frames; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapStoryBoard")]
  public partial class MapStoryBoard : global::ProtoBuf.IExtensible
  {
    public MapStoryBoard() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<MapAnimation> _animations = new global::System.Collections.Generic.List<MapAnimation>();
    [global::ProtoBuf.ProtoMember(2, Name=@"animations", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapAnimation> animations
    {
      get { return _animations; }
    }
  
    private int _beginEventID = (int)-1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"beginEventID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int beginEventID
    {
      get { return _beginEventID; }
      set { _beginEventID = value; }
    }
    private int _endEventID = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"endEventID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int endEventID
    {
      get { return _endEventID; }
      set { _endEventID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}