//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MapEvent.proto
// Note: requires additional types generated from: Math.proto
using Math;

namespace MapEvent
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapItem")]
  public partial class MapItem : global::ProtoBuf.IExtensible
  {
    public MapItem() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _requiredKey = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"requiredKey", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int requiredKey
    {
      get { return _requiredKey; }
      set { _requiredKey = value; }
    }
    private Vector3f _center = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"center", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f center
    {
      get { return _center; }
      set { _center = value; }
    }
    private Vector3f _size = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f size
    {
      get { return _size; }
      set { _size = value; }
    }
    private string _path = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapWall")]
  public partial class MapWall : global::ProtoBuf.IExtensible
  {
    public MapWall() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _requiredKey = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"requiredKey", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int requiredKey
    {
      get { return _requiredKey; }
      set { _requiredKey = value; }
    }
    private Vector3f _center = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"center", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f center
    {
      get { return _center; }
      set { _center = value; }
    }
    private Vector3f _size = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f size
    {
      get { return _size; }
      set { _size = value; }
    }
    private Vector3f _rotation = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private bool _autoshow = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"autoshow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool autoshow
    {
      get { return _autoshow; }
      set { _autoshow = value; }
    }
    private string _effectPath = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"effectPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string effectPath
    {
      get { return _effectPath; }
      set { _effectPath = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ContentValue")]
  public partial class ContentValue : global::ProtoBuf.IExtensible
  {
    public ContentValue() {}
    
    private bool _boolValue = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"boolValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool boolValue
    {
      get { return _boolValue; }
      set { _boolValue = value; }
    }
    private int _intValue = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"intValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int intValue
    {
      get { return _intValue; }
      set { _intValue = value; }
    }
    private string _strValue = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"strValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strValue
    {
      get { return _strValue; }
      set { _strValue = value; }
    }
    private float _floatValue = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"floatValue", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float floatValue
    {
      get { return _floatValue; }
      set { _floatValue = value; }
    }
    private Vector3f _vector3Value = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"vector3Value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f vector3Value
    {
      get { return _vector3Value; }
      set { _vector3Value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapEventAction")]
  public partial class MapEventAction : global::ProtoBuf.IExtensible
  {
    public MapEventAction() {}
    
    private string _target = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string target
    {
      get { return _target; }
      set { _target = value; }
    }
    private MapEventAction.Type _actionType = MapEventAction.Type.UNKNOWN;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"actionType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapEventAction.Type.UNKNOWN)]
    public MapEventAction.Type actionType
    {
      get { return _actionType; }
      set { _actionType = value; }
    }
    private readonly global::System.Collections.Generic.List<ContentValue> _args = new global::System.Collections.Generic.List<ContentValue>();
    [global::ProtoBuf.ProtoMember(3, Name=@"args", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ContentValue> args
    {
      get { return _args; }
    }
  
    private int _delayTime = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"delayTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int delayTime
    {
      get { return _delayTime; }
      set { _delayTime = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN", Value=0)]
      UNKNOWN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLEARWALL", Value=1)]
      CLEARWALL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DROP_ITEM", Value=2)]
      DROP_ITEM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOW_PICKUP", Value=3)]
      SHOW_PICKUP = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HIDE_PICKUP", Value=4)]
      HIDE_PICKUP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOW_NEEDITEM", Value=5)]
      SHOW_NEEDITEM = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HIDE_NEEDITEM", Value=6)]
      HIDE_NEEDITEM = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DESTROY_TRIGGER", Value=7)]
      DESTROY_TRIGGER = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESET_TRIGGER", Value=8)]
      RESET_TRIGGER = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOW_WALL", Value=9)]
      SHOW_WALL = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPEN_NPC_GROUP", Value=10)]
      OPEN_NPC_GROUP = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAY_SEQUENCE", Value=11)]
      PLAY_SEQUENCE = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOW_UI", Value=12)]
      SHOW_UI = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HIDE_UI", Value=13)]
      HIDE_UI = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOW_WAYPOINT", Value=14)]
      SHOW_WAYPOINT = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"START_AUTOFIGHT", Value=15)]
      START_AUTOFIGHT = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STOP_AUTOFIGHT", Value=16)]
      STOP_AUTOFIGHT = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADD_BUFF", Value=17)]
      ADD_BUFF = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHANGE_FRACTION", Value=18)]
      CHANGE_FRACTION = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAY_ACTION", Value=19)]
      PLAY_ACTION = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVE_TO", Value=20)]
      MOVE_TO = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOW_TALK_WORD", Value=21)]
      SHOW_TALK_WORD = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FREEZE_AI", Value=22)]
      FREEZE_AI = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SET_ASBOSS", Value=23)]
      SET_ASBOSS = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEL_BUFF", Value=24)]
      DEL_BUFF = 24
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapEventCondition")]
  public partial class MapEventCondition : global::ProtoBuf.IExtensible
  {
    public MapEventCondition() {}
    
    private MapEventCondition.Condition _type = MapEventCondition.Condition.UNKNOWN;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapEventCondition.Condition.UNKNOWN)]
    public MapEventCondition.Condition type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private ContentValue _arg1 = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"arg1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ContentValue arg1
    {
      get { return _arg1; }
      set { _arg1 = value; }
    }
    private ContentValue _arg2 = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"arg2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ContentValue arg2
    {
      get { return _arg2; }
      set { _arg2 = value; }
    }
    private readonly global::System.Collections.Generic.List<MapEventCondition> _composites = new global::System.Collections.Generic.List<MapEventCondition>();
    [global::ProtoBuf.ProtoMember(5, Name=@"composites", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapEventCondition> composites
    {
      get { return _composites; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Condition")]
    public enum Condition
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN", Value=0)]
      UNKNOWN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUAL", Value=1)]
      EQUAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUAL_NOT", Value=2)]
      EQUAL_NOT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BIGGER", Value=3)]
      BIGGER = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LITTLE", Value=4)]
      LITTLE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BIGGER_EQUAL", Value=5)]
      BIGGER_EQUAL = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LITTLE_EQUAL", Value=6)]
      LITTLE_EQUAL = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONTAIN", Value=7)]
      CONTAIN = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_CONTAIN", Value=8)]
      NOT_CONTAIN = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMPOSITE_OR", Value=9)]
      COMPOSITE_OR = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMPOSITE_AND", Value=9)]
      COMPOSITE_AND = 9
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapEvent")]
  public partial class MapEvent : global::ProtoBuf.IExtensible
  {
    public MapEvent() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _eventType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private string _target = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string target
    {
      get { return _target; }
      set { _target = value; }
    }
    private readonly global::System.Collections.Generic.List<MapEventCondition> _conditions = new global::System.Collections.Generic.List<MapEventCondition>();
    [global::ProtoBuf.ProtoMember(4, Name=@"conditions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapEventCondition> conditions
    {
      get { return _conditions; }
    }
  
    private readonly global::System.Collections.Generic.List<MapEventAction> _actions = new global::System.Collections.Generic.List<MapEventAction>();
    [global::ProtoBuf.ProtoMember(5, Name=@"actions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapEventAction> actions
    {
      get { return _actions; }
    }
  
    private int _executeCount = (int)1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"executeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int executeCount
    {
      get { return _executeCount; }
      set { _executeCount = value; }
    }
    private bool _interception = (bool)false;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"interception", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool interception
    {
      get { return _interception; }
      set { _interception = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapActionTrigger")]
  public partial class MapActionTrigger : global::ProtoBuf.IExtensible
  {
    public MapActionTrigger() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private MapActionTrigger.Type _eventType = MapActionTrigger.Type.UNKNOWN;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"eventType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapActionTrigger.Type.UNKNOWN)]
    public MapActionTrigger.Type eventType
    {
      get { return _eventType; }
      set { _eventType = value; }
    }
    private string _target = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string target
    {
      get { return _target; }
      set { _target = value; }
    }
    private ContentValue _value = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ContentValue value
    {
      get { return _value; }
      set { _value = value; }
    }
    private int _triggerEventId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"triggerEventId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int triggerEventId
    {
      get { return _triggerEventId; }
      set { _triggerEventId = value; }
    }
    private readonly global::System.Collections.Generic.List<MapEventAction> _actions = new global::System.Collections.Generic.List<MapEventAction>();
    [global::ProtoBuf.ProtoMember(6, Name=@"actions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapEventAction> actions
    {
      get { return _actions; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN", Value=0)]
      UNKNOWN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_TRIGGER", Value=1)]
      ENTER_TRIGGER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OUT_TRIGGER", Value=2)]
      OUT_TRIGGER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BORN", Value=3)]
      BORN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEAD", Value=4)]
      DEAD = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PICKUP", Value=5)]
      PICKUP = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USE_ITEM", Value=6)]
      USE_ITEM = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTACK", Value=7)]
      ATTACK = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BEHIT", Value=8)]
      BEHIT = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_SCENE", Value=9)]
      ENTER_SCENE = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEAVE_SCENE", Value=10)]
      LEAVE_SCENE = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DICE_RESULT", Value=11)]
      DICE_RESULT = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STORY_OVER", Value=12)]
      STORY_OVER = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DICE_WINNER", Value=13)]
      DICE_WINNER = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DROP_HP_TO", Value=14)]
      DROP_HP_TO = 14
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapEntityEvent")]
  public partial class MapEntityEvent : global::ProtoBuf.IExtensible
  {
    public MapEntityEvent() {}
    
    private int _targetId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private MapEntityEvent.Type _targetType = MapEntityEvent.Type.UNKNOWN_TYPE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapEntityEvent.Type.UNKNOWN_TYPE)]
    public MapEntityEvent.Type targetType
    {
      get { return _targetType; }
      set { _targetType = value; }
    }
    private readonly global::System.Collections.Generic.List<MapActionTrigger> _triggers = new global::System.Collections.Generic.List<MapActionTrigger>();
    [global::ProtoBuf.ProtoMember(3, Name=@"triggers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapActionTrigger> triggers
    {
      get { return _triggers; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN_TYPE", Value=0)]
      UNKNOWN_TYPE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER", Value=1)]
      PLAYER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NPC", Value=2)]
      NPC = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM", Value=3)]
      ITEM = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WALL", Value=4)]
      WALL = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRIGGER", Value=5)]
      TRIGGER = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM", Value=6)]
      TEAM = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NPCGROUP", Value=7)]
      NPCGROUP = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapTrigger")]
  public partial class MapTrigger : global::ProtoBuf.IExtensible
  {
    public MapTrigger() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private MapTrigger.Type _type = MapTrigger.Type.UNKNOWN_TYPE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapTrigger.Type.UNKNOWN_TYPE)]
    public MapTrigger.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private MapTrigger.Shape _shape = MapTrigger.Shape.UNKNOWN_SHAPE;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"shape", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MapTrigger.Shape.UNKNOWN_SHAPE)]
    public MapTrigger.Shape shape
    {
      get { return _shape; }
      set { _shape = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private Vector3f _center = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"center", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f center
    {
      get { return _center; }
      set { _center = value; }
    }
    private float _radius = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"radius", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float radius
    {
      get { return _radius; }
      set { _radius = value; }
    }
    private Vector3f _size = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f size
    {
      get { return _size; }
      set { _size = value; }
    }
    private Vector3f _rotation = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Vector3f rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private readonly global::System.Collections.Generic.List<MapEventAction> _inActions = new global::System.Collections.Generic.List<MapEventAction>();
    [global::ProtoBuf.ProtoMember(9, Name=@"inActions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapEventAction> inActions
    {
      get { return _inActions; }
    }
  
    private readonly global::System.Collections.Generic.List<MapEventAction> _outActions = new global::System.Collections.Generic.List<MapEventAction>();
    [global::ProtoBuf.ProtoMember(10, Name=@"outActions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapEventAction> outActions
    {
      get { return _outActions; }
    }
  
    private string _objPath = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"objPath", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string objPath
    {
      get { return _objPath; }
      set { _objPath = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN_TYPE", Value=0)]
      UNKNOWN_TYPE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EVENT", Value=1)]
      EVENT = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Shape")]
    public enum Shape
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNOWN_SHAPE", Value=0)]
      UNKNOWN_SHAPE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CIRCLE", Value=1)]
      CIRCLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOX", Value=2)]
      BOX = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapEventData")]
  public partial class MapEventData : global::ProtoBuf.IExtensible
  {
    public MapEventData() {}
    
    private readonly global::System.Collections.Generic.List<MapWall> _walls = new global::System.Collections.Generic.List<MapWall>();
    [global::ProtoBuf.ProtoMember(1, Name=@"walls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapWall> walls
    {
      get { return _walls; }
    }
  
    private readonly global::System.Collections.Generic.List<MapEvent> _events = new global::System.Collections.Generic.List<MapEvent>();
    [global::ProtoBuf.ProtoMember(2, Name=@"events", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapEvent> events
    {
      get { return _events; }
    }
  
    private readonly global::System.Collections.Generic.List<MapTrigger> _triggers = new global::System.Collections.Generic.List<MapTrigger>();
    [global::ProtoBuf.ProtoMember(3, Name=@"triggers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapTrigger> triggers
    {
      get { return _triggers; }
    }
  
    private readonly global::System.Collections.Generic.List<MapEntityEvent> _entityEvents = new global::System.Collections.Generic.List<MapEntityEvent>();
    [global::ProtoBuf.ProtoMember(4, Name=@"entityEvents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapEntityEvent> entityEvents
    {
      get { return _entityEvents; }
    }
  
    private readonly global::System.Collections.Generic.List<MapItem> _items = new global::System.Collections.Generic.List<MapItem>();
    [global::ProtoBuf.ProtoMember(5, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MapItem> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}