//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: NetChat.proto
// Note: requires additional types generated from: NetHeader.proto
namespace NetChat
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CCHATRegister")]
  public partial class CCHATRegister : global::ProtoBuf.IExtensible
  {
    public CCHATRegister() {}
    
    private long _pid = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long pid
    {
      get { return _pid; }
      set { _pid = value; }
    }
    private long _rid = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long rid
    {
      get { return _rid; }
      set { _rid = value; }
    }
    private string _token = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ID")]
    public enum ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRID", Value=21)]
      MRID = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPID", Value=5)]
      GROUPID = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNITID", Value=1)]
      UNITID = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CCHATSendMessage")]
  public partial class CCHATSendMessage : global::ProtoBuf.IExtensible
  {
    public CCHATSendMessage() {}
    
    private ChatType _type = ChatType.CURRENT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ChatType.CURRENT)]
    public ChatType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private long _id1 = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id1
    {
      get { return _id1; }
      set { _id1 = value; }
    }
    private string _charmessage = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"charmessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string charmessage
    {
      get { return _charmessage; }
      set { _charmessage = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ID")]
    public enum ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRID", Value=21)]
      MRID = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPID", Value=5)]
      GROUPID = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNITID", Value=2)]
      UNITID = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHATCRegister")]
  public partial class CHATCRegister : global::ProtoBuf.IExtensible
  {
    public CHATCRegister() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private long _pid = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long pid
    {
      get { return _pid; }
      set { _pid = value; }
    }
    private long _rid = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long rid
    {
      get { return _rid; }
      set { _rid = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ID")]
    public enum ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRID", Value=22)]
      MRID = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPID", Value=5)]
      GROUPID = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNITID", Value=1)]
      UNITID = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHATCSendMessage")]
  public partial class CHATCSendMessage : global::ProtoBuf.IExtensible
  {
    public CHATCSendMessage() {}
    
    private ChatType _type = ChatType.CURRENT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ChatType.CURRENT)]
    public ChatType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _charmessage = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"charmessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string charmessage
    {
      get { return _charmessage; }
      set { _charmessage = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ID")]
    public enum ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRID", Value=22)]
      MRID = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPID", Value=5)]
      GROUPID = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNITID", Value=2)]
      UNITID = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHATCErrorNotify")]
  public partial class CHATCErrorNotify : global::ProtoBuf.IExtensible
  {
    public CHATCErrorNotify() {}
    
    private int _errorcode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ID")]
    public enum ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRID", Value=22)]
      MRID = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPID", Value=5)]
      GROUPID = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNITID", Value=4)]
      UNITID = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ChatType")]
    public enum ChatType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CURRENT", Value=0)]
      CURRENT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM", Value=1)]
      TEAM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUILD", Value=2)]
      GUILD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAMILY", Value=3)]
      FAMILY = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHERPLAYER", Value=4)]
      OTHERPLAYER = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WORLD", Value=5)]
      WORLD = 5
    }
  
}