//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: NetCL.proto
// Note: requires additional types generated from: NetHeader.proto
// Note: requires additional types generated from: MovementAtt.proto
// Note: requires additional types generated from: Math.proto
// Note: requires additional types generated from: PlayerAtt.proto
// Note: requires additional types generated from: NPCAtt.proto
// Note: requires additional types generated from: EquipmentAtt.proto
// Note: requires additional types generated from: FightAtt.proto
// Note: requires additional types generated from: Bag.proto
// Note: requires additional types generated from: Item.proto
// Note: requires additional types generated from: Coin.proto
// Note: requires additional types generated from: Task.proto
using Bag;
using Coin;
using EquipmentAtt;
using NPCAtt;

namespace NetCL
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CLPing")]
    public partial class CLPing : global::ProtoBuf.IExtensible
    {
        public CLPing() { }

        private long _time = default(long);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long time
        {
            get { return _time; }
            set { _time = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 17)]
            MRID = 17,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 1)]
            GROUPID = 1,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 1)]
            UNITID = 1
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CLOpenBag")]
    public partial class CLOpenBag : global::ProtoBuf.IExtensible
    {
        public CLOpenBag() { }

        private BagType _bagType =   BagType.WAREHOUSE;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue( BagType.WAREHOUSE)]
        public BagType bagType
        {
            get { return _bagType; }
            set { _bagType = value; }
        }
        private int _pageNum = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"pageNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int pageNum
        {
            get { return _pageNum; }
            set { _pageNum = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 17)]
            MRID = 17,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 1)]
            UNITID = 1
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CLOpenGrid")]
    public partial class CLOpenGrid : global::ProtoBuf.IExtensible
    {
        public CLOpenGrid() { }

        private BagType _bagType =   BagType.WAREHOUSE;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue( BagType.WAREHOUSE)]
        public BagType bagType
        {
            get { return _bagType; }
            set { _bagType = value; }
        }
        private int _pageNum = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"pageNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int pageNum
        {
            get { return _pageNum; }
            set { _pageNum = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 17)]
            MRID = 17,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 2)]
            UNITID = 2
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CLOpenPage")]
    public partial class CLOpenPage : global::ProtoBuf.IExtensible
    {
        public CLOpenPage() { }

        private BagType _bagType =   BagType.WAREHOUSE;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue( BagType.WAREHOUSE)]
        public BagType bagType
        {
            get { return _bagType; }
            set { _bagType = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 17)]
            MRID = 17,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 3)]
            UNITID = 3
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CLArrangeBag")]
    public partial class CLArrangeBag : global::ProtoBuf.IExtensible
    {
        public CLArrangeBag() { }

        private BagType _bagType =   BagType.WAREHOUSE;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue( BagType.WAREHOUSE)]
        public BagType bagType
        {
            get { return _bagType; }
            set { _bagType = value; }
        }
        private int _pageNum = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"pageNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int pageNum
        {
            get { return _pageNum; }
            set { _pageNum = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 17)]
            MRID = 17,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 4)]
            UNITID = 4
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CLGetPageName")]
    public partial class CLGetPageName : global::ProtoBuf.IExtensible
    {
        public CLGetPageName() { }

        private BagType _bagType =   BagType.WAREHOUSE;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue( BagType.WAREHOUSE)]
        public BagType bagType
        {
            get { return _bagType; }
            set { _bagType = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 17)]
            MRID = 17,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 5)]
            UNITID = 5
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CLUpdatePageName")]
    public partial class CLUpdatePageName : global::ProtoBuf.IExtensible
    {
        public CLUpdatePageName() { }

        private BagType _bagType =   BagType.WAREHOUSE;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue( BagType.WAREHOUSE)]
        public BagType bagType
        {
            get { return _bagType; }
            set { _bagType = value; }
        }
        private int _pageNum = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"pageNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int pageNum
        {
            get { return _pageNum; }
            set { _pageNum = value; }
        }
        private string _pageName = "";
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"pageName", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string pageName
        {
            get { return _pageName; }
            set { _pageName = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 17)]
            MRID = 17,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 6)]
            UNITID = 6
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CLUseItem")]
    public partial class CLUseItem : global::ProtoBuf.IExtensible
    {
        public CLUseItem() { }

        private BagType _bagType =   BagType.WAREHOUSE;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue( BagType.WAREHOUSE)]
        public BagType bagType
        {
            get { return _bagType; }
            set { _bagType = value; }
        }
        private int _pageNum = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"pageNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int pageNum
        {
            get { return _pageNum; }
            set { _pageNum = value; }
        }
        private int _pageIndex = default(int);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"pageIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int pageIndex
        {
            get { return _pageIndex; }
            set { _pageIndex = value; }
        }
        private int _count = default(int);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int count
        {
            get { return _count; }
            set { _count = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 17)]
            MRID = 17,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 7)]
            UNITID = 7
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CLShiftItem")]
    public partial class CLShiftItem : global::ProtoBuf.IExtensible
    {
        public CLShiftItem() { }

        private BagType _bagType =   BagType.WAREHOUSE;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue( BagType.WAREHOUSE)]
        public BagType bagType
        {
            get { return _bagType; }
            set { _bagType = value; }
        }
        private int _pageNum = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"pageNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int pageNum
        {
            get { return _pageNum; }
            set { _pageNum = value; }
        }
        private int _pageIndex = default(int);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"pageIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int pageIndex
        {
            get { return _pageIndex; }
            set { _pageIndex = value; }
        }
        private int _count = default(int);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int count
        {
            get { return _count; }
            set { _count = value; }
        }
        private BagType _targetBagType =   BagType.WAREHOUSE;
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"targetBagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue( BagType.WAREHOUSE)]
        public BagType targetBagType
        {
            get { return _targetBagType; }
            set { _targetBagType = value; }
        }
        private int _targetPageNum = default(int);
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"targetPageNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int targetPageNum
        {
            get { return _targetPageNum; }
            set { _targetPageNum = value; }
        }
        private int _targetPageIndex = default(int);
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"targetPageIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int targetPageIndex
        {
            get { return _targetPageIndex; }
            set { _targetPageIndex = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 17)]
            MRID = 17,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 8)]
            UNITID = 8
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CLActiveEquipmentStrategy")]
    public partial class CLActiveEquipmentStrategy : global::ProtoBuf.IExtensible
    {
        public CLActiveEquipmentStrategy() { }

        private int _activePage = default(int);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"activePage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int activePage
        {
            get { return _activePage; }
            set { _activePage = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 17)]
            MRID = 17,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 9)]
            UNITID = 9
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CLTaskOperation")]
    public partial class CLTaskOperation : global::ProtoBuf.IExtensible
    {
        public CLTaskOperation() { }

        private int _taskID = default(int);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"taskID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int taskID
        {
            get { return _taskID; }
            set { _taskID = value; }
        }
        private CLTaskOperation.Operation _operation = CLTaskOperation.Operation.NONE;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"operation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(CLTaskOperation.Operation.NONE)]
        public CLTaskOperation.Operation operation
        {
            get { return _operation; }
            set { _operation = value; }
        }
        private int _param1 = default(int);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"param1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int param1
        {
            get { return _param1; }
            set { _param1 = value; }
        }
        private int _param2 = default(int);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"param2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int param2
        {
            get { return _param2; }
            set { _param2 = value; }
        }
        private int _param3 = default(int);
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"param3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int param3
        {
            get { return _param3; }
            set { _param3 = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 17)]
            MRID = 17,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 3)]
            GROUPID = 3,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 1)]
            UNITID = 1
        }

        [global::ProtoBuf.ProtoContract(Name = @"Operation")]
        public enum Operation
        {

            [global::ProtoBuf.ProtoEnum(Name = @"NONE", Value = 0)]
            NONE = 0,

            [global::ProtoBuf.ProtoEnum(Name = @"ACCEPT", Value = 1)]
            ACCEPT = 1,

            [global::ProtoBuf.ProtoEnum(Name = @"ABOUNDAN", Value = 2)]
            ABOUNDAN = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"TRIGGER", Value = 3)]
            TRIGGER = 3,

            [global::ProtoBuf.ProtoEnum(Name = @"SUBMIT", Value = 4)]
            SUBMIT = 4,

            [global::ProtoBuf.ProtoEnum(Name = @"GET_REWARD", Value = 5)]
            GET_REWARD = 5,

            [global::ProtoBuf.ProtoEnum(Name = @"NEW", Value = 6)]
            NEW = 6,

            [global::ProtoBuf.ProtoEnum(Name = @"UPDATE", Value = 7)]
            UPDATE = 7,

            [global::ProtoBuf.ProtoEnum(Name = @"REMOVE", Value = 8)]
            REMOVE = 8
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CLTaskList")]
    public partial class CLTaskList : global::ProtoBuf.IExtensible
    {
        public CLTaskList() { }

        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 17)]
            MRID = 17,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 3)]
            GROUPID = 3,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 2)]
            UNITID = 2
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CLGetNPCFunc")]
    public partial class CLGetNPCFunc : global::ProtoBuf.IExtensible
    {
        public CLGetNPCFunc() { }

        private int _mapID = default(int);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"mapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int mapID
        {
            get { return _mapID; }
            set { _mapID = value; }
        }
        private int _npcID = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"npcID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int npcID
        {
            get { return _npcID; }
            set { _npcID = value; }
        }
        private readonly global::System.Collections.Generic.List<NPCFunc.Type> _filters = new global::System.Collections.Generic.List<NPCFunc.Type>();
        [global::ProtoBuf.ProtoMember(3, Name = @"filters", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public global::System.Collections.Generic.List<NPCFunc.Type> filters
        {
            get { return _filters; }
        }

        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 17)]
            MRID = 17,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 3)]
            GROUPID = 3,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 3)]
            UNITID = 3
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCPong")]
    public partial class LCPong : global::ProtoBuf.IExtensible
    {
        public LCPong() { }

        private long _time = default(long);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(long))]
        public long time
        {
            get { return _time; }
            set { _time = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 1)]
            GROUPID = 1,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 1)]
            UNITID = 1
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCOpenBag")]
    public partial class LCOpenBag : global::ProtoBuf.IExtensible
    {
        public LCOpenBag() { }

        private BagPage _bagPage = null;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"bagPage", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public BagPage bagPage
        {
            get { return _bagPage; }
            set { _bagPage = value; }
        }
        private BagType _bagType =   BagType.WAREHOUSE;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue( BagType.WAREHOUSE)]
        public BagType bagType
        {
            get { return _bagType; }
            set { _bagType = value; }
        }
        private int _pageNum = default(int);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"pageNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int pageNum
        {
            get { return _pageNum; }
            set { _pageNum = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 1)]
            UNITID = 1
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCOpenGrid")]
    public partial class LCOpenGrid : global::ProtoBuf.IExtensible
    {
        public LCOpenGrid() { }

        private LCOpenGrid.OpenGridResult _result = LCOpenGrid.OpenGridResult.SUCCESS;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(LCOpenGrid.OpenGridResult.SUCCESS)]
        public LCOpenGrid.OpenGridResult result
        {
            get { return _result; }
            set { _result = value; }
        }
        private int _gridCount = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"gridCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int gridCount
        {
            get { return _gridCount; }
            set { _gridCount = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 2)]
            UNITID = 2
        }

        [global::ProtoBuf.ProtoContract(Name = @"OpenGridResult")]
        public enum OpenGridResult
        {

            [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS", Value = 0)]
            SUCCESS = 0,

            [global::ProtoBuf.ProtoEnum(Name = @"FAIL_ALLOPEN", Value = 1)]
            FAIL_ALLOPEN = 1,

            [global::ProtoBuf.ProtoEnum(Name = @"FAIL_NOTNEED", Value = 2)]
            FAIL_NOTNEED = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"FAIL_PARAM", Value = 3)]
            FAIL_PARAM = 3,

            [global::ProtoBuf.ProtoEnum(Name = @"FAIL_NOT_SUPPORT", Value = 4)]
            FAIL_NOT_SUPPORT = 4
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCOpenPage")]
    public partial class LCOpenPage : global::ProtoBuf.IExtensible
    {
        public LCOpenPage() { }

        private LCOpenPage.OpenPageResult _result = LCOpenPage.OpenPageResult.SUCCESS;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(LCOpenPage.OpenPageResult.SUCCESS)]
        public LCOpenPage.OpenPageResult result
        {
            get { return _result; }
            set { _result = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 3)]
            UNITID = 3
        }

        [global::ProtoBuf.ProtoContract(Name = @"OpenPageResult")]
        public enum OpenPageResult
        {

            [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS", Value = 0)]
            SUCCESS = 0,

            [global::ProtoBuf.ProtoEnum(Name = @"FAIL_ALLOPEN", Value = 1)]
            FAIL_ALLOPEN = 1,

            [global::ProtoBuf.ProtoEnum(Name = @"FAIL_NOTNEED", Value = 2)]
            FAIL_NOTNEED = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"FAIL_NOTSUPPORT", Value = 3)]
            FAIL_NOTSUPPORT = 3,

            [global::ProtoBuf.ProtoEnum(Name = @"FAIL_PARAM", Value = 4)]
            FAIL_PARAM = 4
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCGetPageName")]
    public partial class LCGetPageName : global::ProtoBuf.IExtensible
    {
        public LCGetPageName() { }

        private readonly global::System.Collections.Generic.List<string> _pageNameList = new global::System.Collections.Generic.List<string>();
        [global::ProtoBuf.ProtoMember(1, Name = @"pageNameList", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<string> pageNameList
        {
            get { return _pageNameList; }
        }

        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 4)]
            UNITID = 4
        }

        [global::ProtoBuf.ProtoContract(Name = @"GetPageNameResult")]
        public enum GetPageNameResult
        {

            [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS", Value = 0)]
            SUCCESS = 0,

            [global::ProtoBuf.ProtoEnum(Name = @"FAIL_NOTFOUND", Value = 1)]
            FAIL_NOTFOUND = 1,

            [global::ProtoBuf.ProtoEnum(Name = @"FAIL_NOTSUPPORT", Value = 2)]
            FAIL_NOTSUPPORT = 2
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCUpdateGrid")]
    public partial class LCUpdateGrid : global::ProtoBuf.IExtensible
    {
        public LCUpdateGrid() { }

        private BagType _bagType =   BagType.WAREHOUSE;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue( BagType.WAREHOUSE)]
        public BagType bagType
        {
            get { return _bagType; }
            set { _bagType = value; }
        }
        private int _pageNum = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"pageNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int pageNum
        {
            get { return _pageNum; }
            set { _pageNum = value; }
        }
        private readonly global::System.Collections.Generic.List<int> _gridNum = new global::System.Collections.Generic.List<int>();
        [global::ProtoBuf.ProtoMember(3, Name = @"gridNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public global::System.Collections.Generic.List<int> gridNum
        {
            get { return _gridNum; }
        }

        private readonly global::System.Collections.Generic.List<Item.Item> _grid = new global::System.Collections.Generic.List<Item.Item>();
        [global::ProtoBuf.ProtoMember(4, Name = @"grid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Item.Item> grid
        {
            get { return _grid; }
        }

        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 5)]
            UNITID = 5
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCUpdatePageName")]
    public partial class LCUpdatePageName : global::ProtoBuf.IExtensible
    {
        public LCUpdatePageName() { }

        private LCUpdatePageName.UpdatePageNameResult _result = LCUpdatePageName.UpdatePageNameResult.SUCCESS;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(LCUpdatePageName.UpdatePageNameResult.SUCCESS)]
        public LCUpdatePageName.UpdatePageNameResult result
        {
            get { return _result; }
            set { _result = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 6)]
            UNITID = 6
        }

        [global::ProtoBuf.ProtoContract(Name = @"UpdatePageNameResult")]
        public enum UpdatePageNameResult
        {

            [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS", Value = 0)]
            SUCCESS = 0,

            [global::ProtoBuf.ProtoEnum(Name = @"FAIL", Value = 1)]
            FAIL = 1
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCArrangeBag")]
    public partial class LCArrangeBag : global::ProtoBuf.IExtensible
    {
        public LCArrangeBag() { }

        private BagPage _bagPage = null;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"bagPage", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public BagPage bagPage
        {
            get { return _bagPage; }
            set { _bagPage = value; }
        }
        private LCArrangeBag.ArrangeBagResult _result = LCArrangeBag.ArrangeBagResult.SUCCESS_CHANGE;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(LCArrangeBag.ArrangeBagResult.SUCCESS_CHANGE)]
        public LCArrangeBag.ArrangeBagResult result
        {
            get { return _result; }
            set { _result = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 7)]
            UNITID = 7
        }

        [global::ProtoBuf.ProtoContract(Name = @"ArrangeBagResult")]
        public enum ArrangeBagResult
        {

            [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS_CHANGE", Value = 1)]
            SUCCESS_CHANGE = 1,

            [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS_NOT_CHANGE", Value = 2)]
            SUCCESS_NOT_CHANGE = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"FAIL_PARAM", Value = 3)]
            FAIL_PARAM = 3
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCUseItem")]
    public partial class LCUseItem : global::ProtoBuf.IExtensible
    {
        public LCUseItem() { }

        private BagType _bagType =   BagType.WAREHOUSE;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue( BagType.WAREHOUSE)]
        public BagType bagType
        {
            get { return _bagType; }
            set { _bagType = value; }
        }
        private int _pageNum = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"pageNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int pageNum
        {
            get { return _pageNum; }
            set { _pageNum = value; }
        }
        private int _pageIndex = default(int);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"pageIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int pageIndex
        {
            get { return _pageIndex; }
            set { _pageIndex = value; }
        }
        private int _count = default(int);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int count
        {
            get { return _count; }
            set { _count = value; }
        }
        private LCUseItem.UseItemResult _result = LCUseItem.UseItemResult.SUCCESS;
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(LCUseItem.UseItemResult.SUCCESS)]
        public LCUseItem.UseItemResult result
        {
            get { return _result; }
            set { _result = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 8)]
            UNITID = 8
        }

        [global::ProtoBuf.ProtoContract(Name = @"UseItemResult")]
        public enum UseItemResult
        {

            [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS", Value = 0)]
            SUCCESS = 0,

            [global::ProtoBuf.ProtoEnum(Name = @"NOTHAVEITEM", Value = 1)]
            NOTHAVEITEM = 1,

            [global::ProtoBuf.ProtoEnum(Name = @"NOTENOUGH", Value = 2)]
            NOTENOUGH = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"CANTUSE", Value = 3)]
            CANTUSE = 3
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCShiftItem")]
    public partial class LCShiftItem : global::ProtoBuf.IExtensible
    {
        public LCShiftItem() { }

        private BagType _bagType =   BagType.WAREHOUSE;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(  BagType.WAREHOUSE)]
        public BagType bagType
        {
            get { return _bagType; }
            set { _bagType = value; }
        }
        private int _pageNum = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"pageNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int pageNum
        {
            get { return _pageNum; }
            set { _pageNum = value; }
        }
        private int _pageIndex = default(int);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"pageIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int pageIndex
        {
            get { return _pageIndex; }
            set { _pageIndex = value; }
        }
        private int _count = default(int);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int count
        {
            get { return _count; }
            set { _count = value; }
        }
        private BagType _targetBagType =   BagType.WAREHOUSE;
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"targetBagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(  BagType.WAREHOUSE)]
        public BagType targetBagType
        {
            get { return _targetBagType; }
            set { _targetBagType = value; }
        }
        private int _targetPageNum = default(int);
        [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"targetPageNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int targetPageNum
        {
            get { return _targetPageNum; }
            set { _targetPageNum = value; }
        }
        private int _targetPageIndex = default(int);
        [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"targetPageIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int targetPageIndex
        {
            get { return _targetPageIndex; }
            set { _targetPageIndex = value; }
        }
        private LCShiftItem.ShiftItemResult _result = LCShiftItem.ShiftItemResult.SUCCESS;
        [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(LCShiftItem.ShiftItemResult.SUCCESS)]
        public LCShiftItem.ShiftItemResult result
        {
            get { return _result; }
            set { _result = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 9)]
            UNITID = 9
        }

        [global::ProtoBuf.ProtoContract(Name = @"ShiftItemResult")]
        public enum ShiftItemResult
        {

            [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS", Value = 0)]
            SUCCESS = 0,

            [global::ProtoBuf.ProtoEnum(Name = @"NOTHAVEITEM", Value = 1)]
            NOTHAVEITEM = 1,

            [global::ProtoBuf.ProtoEnum(Name = @"NOTENOUGH", Value = 2)]
            NOTENOUGH = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"NOTHAVEEQUIPASSET", Value = 3)]
            NOTHAVEEQUIPASSET = 3,

            [global::ProtoBuf.ProtoEnum(Name = @"INVALIDEQUIPASSET", Value = 4)]
            INVALIDEQUIPASSET = 4,

            [global::ProtoBuf.ProtoEnum(Name = @"INVALIDEQUIPPOS", Value = 5)]
            INVALIDEQUIPPOS = 5,

            [global::ProtoBuf.ProtoEnum(Name = @"OTHER", Value = 6)]
            OTHER = 6
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCActiveEquipmentStrategy")]
    public partial class LCActiveEquipmentStrategy : global::ProtoBuf.IExtensible
    {
        public LCActiveEquipmentStrategy() { }

        private int _activePage = default(int);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"activePage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int activePage
        {
            get { return _activePage; }
            set { _activePage = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 11)]
            UNITID = 11
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCUpdateCoinCount")]
    public partial class LCUpdateCoinCount : global::ProtoBuf.IExtensible
    {
        public LCUpdateCoinCount() { }

        private CoinType _coinType = CoinType.GOLD;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"coinType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(CoinType.GOLD)]
        public CoinType coinType
        {
            get { return _coinType; }
            set { _coinType = value; }
        }
        private int _coinValue = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"coinValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int coinValue
        {
            get { return _coinValue; }
            set { _coinValue = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 12)]
            UNITID = 12
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCUpdateEquip")]
    public partial class LCUpdateEquip : global::ProtoBuf.IExtensible
    {
        public LCUpdateEquip() { }

        private readonly global::System.Collections.Generic.List<int> _ids = new global::System.Collections.Generic.List<int>();
        [global::ProtoBuf.ProtoMember(1, Name = @"ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public global::System.Collections.Generic.List<int> ids
        {
            get { return _ids; }
        }

        private readonly global::System.Collections.Generic.List<EquipmentAsset> _equipmentes = new global::System.Collections.Generic.List<EquipmentAsset>();
        [global::ProtoBuf.ProtoMember(2, Name = @"equipmentes", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<EquipmentAsset> equipmentes
        {
            get { return _equipmentes; }
        }

        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 2)]
            GROUPID = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 13)]
            UNITID = 13
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCTask")]
    public partial class LCTask : global::ProtoBuf.IExtensible
    {
        public LCTask() { }

        private Task.Task _task = null;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"task", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public Task.Task task
        {
            get { return _task; }
            set { _task = value; }
        }
        private readonly global::System.Collections.Generic.List<Item.Item> _drop = new global::System.Collections.Generic.List<Item.Item>();
        [global::ProtoBuf.ProtoMember(2, Name = @"drop", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Item.Item> drop
        {
            get { return _drop; }
        }

        private int _ingotCount = default(int);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"ingotCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int ingotCount
        {
            get { return _ingotCount; }
            set { _ingotCount = value; }
        }
        private int _goldCount = default(int);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"goldCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int goldCount
        {
            get { return _goldCount; }
            set { _goldCount = value; }
        }
        private int _silverCount = default(int);
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"silverCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int silverCount
        {
            get { return _silverCount; }
            set { _silverCount = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 3)]
            GROUPID = 3,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 1)]
            UNITID = 1
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCTaskList")]
    public partial class LCTaskList : global::ProtoBuf.IExtensible
    {
        public LCTaskList() { }

        private readonly global::System.Collections.Generic.List<Task.Task> _tasks = new global::System.Collections.Generic.List<Task.Task>();
        [global::ProtoBuf.ProtoMember(1, Name = @"tasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Task.Task> tasks
        {
            get { return _tasks; }
        }

        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 3)]
            GROUPID = 3,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 2)]
            UNITID = 2
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCTaskOperationResult")]
    public partial class LCTaskOperationResult : global::ProtoBuf.IExtensible
    {
        public LCTaskOperationResult() { }

        private Task.Task _task = null;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"task", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public Task.Task task
        {
            get { return _task; }
            set { _task = value; }
        }
        private int _result = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int result
        {
            get { return _result; }
            set { _result = value; }
        }
        private string _error = "";
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string error
        {
            get { return _error; }
            set { _error = value; }
        }
        private CLTaskOperation.Operation _operation = CLTaskOperation.Operation.NONE;
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"operation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(CLTaskOperation.Operation.NONE)]
        public CLTaskOperation.Operation operation
        {
            get { return _operation; }
            set { _operation = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 3)]
            GROUPID = 3,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 3)]
            UNITID = 3
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"LCNPCFuncs")]
    public partial class LCNPCFuncs : global::ProtoBuf.IExtensible
    {
        public LCNPCFuncs() { }

        private int _mapID = default(int);
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"mapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int mapID
        {
            get { return _mapID; }
            set { _mapID = value; }
        }
        private int _npcID = default(int);
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"npcID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int npcID
        {
            get { return _npcID; }
            set { _npcID = value; }
        }
        private readonly global::System.Collections.Generic.List<NPCFunc> _funcs = new global::System.Collections.Generic.List<NPCFunc>();
        [global::ProtoBuf.ProtoMember(3, Name = @"funcs", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<NPCFunc> funcs
        {
            get { return _funcs; }
        }

        [global::ProtoBuf.ProtoContract(Name = @"ID")]
        public enum ID
        {

            [global::ProtoBuf.ProtoEnum(Name = @"MRID", Value = 18)]
            MRID = 18,

            [global::ProtoBuf.ProtoEnum(Name = @"GROUPID", Value = 3)]
            GROUPID = 3,

            [global::ProtoBuf.ProtoEnum(Name = @"UNITID", Value = 4)]
            UNITID = 4
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
}
  
