//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: NetCH.proto
// Note: requires additional types generated from: NetHeader.proto
// Note: requires additional types generated from: BaseAtt.proto
namespace NetCH
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"URLAddr")]
  public partial class URLAddr : global::ProtoBuf.IExtensible
  {
    public URLAddr() {}
    
    private string _url = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string url
    {
      get { return _url; }
      set { _url = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SocketAddr")]
  public partial class SocketAddr : global::ProtoBuf.IExtensible
  {
    public SocketAddr() {}
    
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _port = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerInfo")]
  public partial class ServerInfo : global::ProtoBuf.IExtensible
  {
    public ServerInfo() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ServerInfo.Status _status = ServerInfo.Status.CLOSE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ServerInfo.Status.CLOSE)]
    public ServerInfo.Status status
    {
      get { return _status; }
      set { _status = value; }
    }
    private URLAddr _http = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"http", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public URLAddr http
    {
      get { return _http; }
      set { _http = value; }
    }
    private SocketAddr _gate = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SocketAddr gate
    {
      get { return _gate; }
      set { _gate = value; }
    }
    private ServerInfo.Type _type = ServerInfo.Type.COMMON;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ServerInfo.Type.COMMON)]
    public ServerInfo.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _roleidlist = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"roleidlist", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> roleidlist
    {
      get { return _roleidlist; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Status")]
    public enum Status
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLOSE", Value=0)]
      CLOSE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FREE", Value=1)]
      FREE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUSY", Value=2)]
      BUSY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FULL", Value=3)]
      FULL = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMON", Value=0)]
      COMMON = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RECOMMEND", Value=1)]
      RECOMMEND = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEW", Value=2)]
      NEW = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHLogin")]
  public partial class CHLogin : global::ProtoBuf.IExtensible
  {
    public CHLogin() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ID")]
    public enum ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRID", Value=10)]
      MRID = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPID", Value=2)]
      GROUPID = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNITID", Value=1)]
      UNITID = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHCreateRole")]
  public partial class CHCreateRole : global::ProtoBuf.IExtensible
  {
    public CHCreateRole() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private long _userid = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private int _profession = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"profession", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int profession
    {
      get { return _profession; }
      set { _profession = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ID")]
    public enum ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRID", Value=10)]
      MRID = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPID", Value=2)]
      GROUPID = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNITID", Value=2)]
      UNITID = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHServerList")]
  public partial class CHServerList : global::ProtoBuf.IExtensible
  {
    public CHServerList() {}
    
    private int _server = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"server", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int server
    {
      get { return _server; }
      set { _server = value; }
    }
    private long _playerid = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ID")]
    public enum ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRID", Value=10)]
      MRID = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPID", Value=2)]
      GROUPID = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNITID", Value=3)]
      UNITID = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CHRoleList")]
  public partial class CHRoleList : global::ProtoBuf.IExtensible
  {
    public CHRoleList() {}
    
    private int _isnew = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isnew", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isnew
    {
      get { return _isnew; }
      set { _isnew = value; }
    }
    private long _userid = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ID")]
    public enum ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRID", Value=10)]
      MRID = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPID", Value=2)]
      GROUPID = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNITID", Value=4)]
      UNITID = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HCLogin")]
  public partial class HCLogin : global::ProtoBuf.IExtensible
  {
    public HCLogin() {}
    
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _token = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ID")]
    public enum ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRID", Value=11)]
      MRID = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPID", Value=2)]
      GROUPID = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNITID", Value=1)]
      UNITID = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HCCreateRole")]
  public partial class HCCreateRole : global::ProtoBuf.IExtensible
  {
    public HCCreateRole() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ID")]
    public enum ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRID", Value=11)]
      MRID = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPID", Value=2)]
      GROUPID = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNITID", Value=2)]
      UNITID = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HCServerList")]
  public partial class HCServerList : global::ProtoBuf.IExtensible
  {
    public HCServerList() {}
    
    private readonly global::System.Collections.Generic.List<ServerInfo> _servers = new global::System.Collections.Generic.List<ServerInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"servers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ServerInfo> servers
    {
      get { return _servers; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ID")]
    public enum ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRID", Value=11)]
      MRID = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPID", Value=2)]
      GROUPID = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNITID", Value=3)]
      UNITID = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HCRoleList")]
  public partial class HCRoleList : global::ProtoBuf.IExtensible
  {
    public HCRoleList() {}
    
    private readonly global::System.Collections.Generic.List<int> _index = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> index
    {
      get { return _index; }
    }
  
    private readonly global::System.Collections.Generic.List<BaseAtt.BaseAtt> _atts = new global::System.Collections.Generic.List<BaseAtt.BaseAtt>();
    [global::ProtoBuf.ProtoMember(2, Name=@"atts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BaseAtt.BaseAtt> atts
    {
      get { return _atts; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ID")]
    public enum ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MRID", Value=11)]
      MRID = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUPID", Value=2)]
      GROUPID = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNITID", Value=4)]
      UNITID = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}