//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SkillInfo.proto
// Note: requires additional types generated from: Item.proto
// Note: requires additional types generated from: StringID.proto
using StringID;

namespace SkillInfo
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillLevelInfo")]
  public partial class SkillLevelInfo : global::ProtoBuf.IExtensible
  {
    public SkillLevelInfo() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _unit = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"unit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int unit
    {
      get { return _unit; }
      set { _unit = value; }
    }
    private int _learnRequireLevel = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"learnRequireLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int learnRequireLevel
    {
      get { return _learnRequireLevel; }
      set { _learnRequireLevel = value; }
    }
    private readonly global::System.Collections.Generic.List<Item.Item> _learnNeeds = new global::System.Collections.Generic.List<Item.Item>();
    [global::ProtoBuf.ProtoMember(5, Name=@"learnNeeds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Item.Item> learnNeeds
    {
      get { return _learnNeeds; }
    }
  
    private int _icon = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private int _fightingValue = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fightingValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fightingValue
    {
      get { return _fightingValue; }
      set { _fightingValue = value; }
    }
    private readonly global::System.Collections.Generic.List<Item.Item> _releaseNeeds = new global::System.Collections.Generic.List<Item.Item>();
    [global::ProtoBuf.ProtoMember(8, Name=@"releaseNeeds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Item.Item> releaseNeeds
    {
      get { return _releaseNeeds; }
    }
  
    private int _targetNPC = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"targetNPC", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int targetNPC
    {
      get { return _targetNPC; }
      set { _targetNPC = value; }
    }
    private SkillLevelInfo.TargetFactor _targetFactor = SkillLevelInfo.TargetFactor.TARGETFACTOR_NONE;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"targetFactor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(SkillLevelInfo.TargetFactor.TARGETFACTOR_NONE)]
    public SkillLevelInfo.TargetFactor targetFactor
    {
      get { return _targetFactor; }
      set { _targetFactor = value; }
    }
    private int _factorParam = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"factorParam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int factorParam
    {
      get { return _factorParam; }
      set { _factorParam = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"TargetFactor")]
    public enum TargetFactor
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TARGETFACTOR_NONE", Value=0)]
      TARGETFACTOR_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS", Value=1)]
      STATUS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HP", Value=2)]
      HP = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillInfo")]
  public partial class SkillInfo : global::ProtoBuf.IExtensible
  {
    public SkillInfo() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _desc = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private SkillInfo.MajorType _majorType = SkillInfo.MajorType.NONE;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"majorType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(SkillInfo.MajorType.NONE)]
    public SkillInfo.MajorType majorType
    {
      get { return _majorType; }
      set { _majorType = value; }
    }
    private int _minorType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"minorType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minorType
    {
      get { return _minorType; }
      set { _minorType = value; }
    }
    private bool _initiative = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"initiative", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool initiative
    {
      get { return _initiative; }
      set { _initiative = value; }
    }
    private SkillInfo.EnvScene _env = SkillInfo.EnvScene.ENV_NONE;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"env", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(SkillInfo.EnvScene.ENV_NONE)]
    public SkillInfo.EnvScene env
    {
      get { return _env; }
      set { _env = value; }
    }
    private int _envParam = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"envParam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int envParam
    {
      get { return _envParam; }
      set { _envParam = value; }
    }
    private int _beginAudio = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"beginAudio", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int beginAudio
    {
      get { return _beginAudio; }
      set { _beginAudio = value; }
    }
    private int _hitAudio = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"hitAudio", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hitAudio
    {
      get { return _hitAudio; }
      set { _hitAudio = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MajorType")]
    public enum MajorType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=0)]
      NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROFESSION", Value=1)]
      PROFESSION = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LIFE", Value=2)]
      LIFE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CARRIER", Value=3)]
      CARRIER = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNION", Value=4)]
      UNION = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOODS", Value=5)]
      GOODS = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NPC", Value=6)]
      NPC = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUNC", Value=7)]
      FUNC = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER", Value=8)]
      OTHER = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EnvScene")]
    public enum EnvScene
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENV_NONE", Value=0)]
      ENV_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL", Value=1)]
      ALL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROUTIN", Value=2)]
      ROUTIN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY", Value=3)]
      ACTIVITY = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"APPOINT", Value=4)]
      APPOINT = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkillLevels")]
  public partial class SkillLevels : global::ProtoBuf.IExtensible
  {
    public SkillLevels() {}
    
    private readonly global::System.Collections.Generic.List<SkillLevelInfo> _levels = new global::System.Collections.Generic.List<SkillLevelInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"levels", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SkillLevelInfo> levels
    {
      get { return _levels; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllSkillLevels")]
  public partial class AllSkillLevels : global::ProtoBuf.IExtensible
  {
    public AllSkillLevels() {}
    
    private readonly global::System.Collections.Generic.List<SkillLevels> _levels = new global::System.Collections.Generic.List<SkillLevels>();
    [global::ProtoBuf.ProtoMember(1, Name=@"levels", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SkillLevels> levels
    {
      get { return _levels; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllSkills")]
  public partial class AllSkills : global::ProtoBuf.IExtensible
  {
    public AllSkills() {}
    
    private readonly global::System.Collections.Generic.List<SkillInfo> _skills = new global::System.Collections.Generic.List<SkillInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"skills", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SkillInfo> skills
    {
      get { return _skills; }
    }
  
    private AllStringID _stringID = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stringID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AllStringID stringID
    {
      get { return _stringID; }
      set { _stringID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}