//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Task.proto
// Note: requires additional types generated from: Item.proto
// Note: requires additional types generated from: StringID.proto
using StringID;

namespace Task
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Task")]
  public partial class Task : global::ProtoBuf.IExtensible
  {
    public Task() {}
    
    private int _taskID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"taskID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int taskID
    {
      get { return _taskID; }
      set { _taskID = value; }
    }
    private Task.TaskStatus _taskStatus = Task.TaskStatus.UNAVAILABLE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"taskStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Task.TaskStatus.UNAVAILABLE)]
    public Task.TaskStatus taskStatus
    {
      get { return _taskStatus; }
      set { _taskStatus = value; }
    }
    private int _startTime = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private int _endTime = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private int _rewardTime = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rewardTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rewardTime
    {
      get { return _rewardTime; }
      set { _rewardTime = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _progress = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"progress", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> progress
    {
      get { return _progress; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _arrived = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(7, Name=@"arrived", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> arrived
    {
      get { return _arrived; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _completed = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(8, Name=@"completed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> completed
    {
      get { return _completed; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TaskStatus")]
    public enum TaskStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNAVAILABLE", Value=0)]
      UNAVAILABLE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AVAILABLE", Value=1)]
      AVAILABLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCEPTED", Value=2)]
      ACCEPTED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DOING", Value=3)]
      DOING = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMPLETE", Value=4)]
      COMPLETE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REWARD", Value=5)]
      REWARD = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ABOUNDAND", Value=6)]
      ABOUNDAND = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExtensionCondition")]
  public partial class ExtensionCondition : global::ProtoBuf.IExtensible
  {
    public ExtensionCondition() {}
    
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _param1 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"param1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int param1
    {
      get { return _param1; }
      set { _param1 = value; }
    }
    private int _param2 = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"param2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int param2
    {
      get { return _param2; }
      set { _param2 = value; }
    }
    private int _param3 = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"param3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int param3
    {
      get { return _param3; }
      set { _param3 = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEVEL", Value=1)]
      LEVEL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCHOOL", Value=2)]
      SCHOOL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCHOOL_TITLE", Value=3)]
      SCHOOL_TITLE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GENDER", Value=4)]
      GENDER = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS", Value=5)]
      STATUS = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HELPER", Value=6)]
      HELPER = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PET", Value=7)]
      PET = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRESTIGE", Value=8)]
      PRESTIGE = 8
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskCondition")]
  public partial class TaskCondition : global::ProtoBuf.IExtensible
  {
    public TaskCondition() {}
    
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _teamCount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"teamCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int teamCount
    {
      get { return _teamCount; }
      set { _teamCount = value; }
    }
    private int _school = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"school", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int school
    {
      get { return _school; }
      set { _school = value; }
    }
    private bool _inGroup = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"inGroup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool inGroup
    {
      get { return _inGroup; }
      set { _inGroup = value; }
    }
    private int _power = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int power
    {
      get { return _power; }
      set { _power = value; }
    }
    private int _itemID = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"itemID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemID
    {
      get { return _itemID; }
      set { _itemID = value; }
    }
    private readonly global::System.Collections.Generic.List<ExtensionCondition> _extentions = new global::System.Collections.Generic.List<ExtensionCondition>();
    [global::ProtoBuf.ProtoMember(7, Name=@"extentions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ExtensionCondition> extentions
    {
      get { return _extentions; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskLocation")]
  public partial class TaskLocation : global::ProtoBuf.IExtensible
  {
    public TaskLocation() {}
    
    private int _mapID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mapID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mapID
    {
      get { return _mapID; }
      set { _mapID = value; }
    }
    private int _npcID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"npcID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int npcID
    {
      get { return _npcID; }
      set { _npcID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskAcceptPolicy")]
  public partial class TaskAcceptPolicy : global::ProtoBuf.IExtensible
  {
    public TaskAcceptPolicy() {}
    
    private TaskLocation _location = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"location", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TaskLocation location
    {
      get { return _location; }
      set { _location = value; }
    }
    private Item.Item _itemGot = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemGot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Item.Item itemGot
    {
      get { return _itemGot; }
      set { _itemGot = value; }
    }
    private int _funcID = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"funcID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int funcID
    {
      get { return _funcID; }
      set { _funcID = value; }
    }
    private string _storyName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"storyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string storyName
    {
      get { return _storyName; }
      set { _storyName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskLimit")]
  public partial class TaskLimit : global::ProtoBuf.IExtensible
  {
    public TaskLimit() {}
    
    private bool _canRetry = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"canRetry", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool canRetry
    {
      get { return _canRetry; }
      set { _canRetry = value; }
    }
    private bool _canAbandon = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"canAbandon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool canAbandon
    {
      get { return _canAbandon; }
      set { _canAbandon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoalCondition")]
  public partial class GoalCondition : global::ProtoBuf.IExtensible
  {
    public GoalCondition() {}
    
    private int _type = (int)-1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _param1 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"param1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int param1
    {
      get { return _param1; }
      set { _param1 = value; }
    }
    private int _param2 = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"param2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int param2
    {
      get { return _param2; }
      set { _param2 = value; }
    }
    private int _param3 = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"param3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int param3
    {
      get { return _param3; }
      set { _param3 = value; }
    }
    private int _param4 = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"param4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int param4
    {
      get { return _param4; }
      set { _param4 = value; }
    }
    private int _param5 = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"param5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int param5
    {
      get { return _param5; }
      set { _param5 = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEED_ITEM", Value=0)]
      NEED_ITEM = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KILL_MONSTER", Value=1)]
      KILL_MONSTER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEVEL", Value=2)]
      LEVEL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TASK_COUNT", Value=3)]
      TASK_COUNT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIALOG", Value=4)]
      DIALOG = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHANGE_PRO", Value=5)]
      CHANGE_PRO = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USE_ITEM", Value=6)]
      USE_ITEM = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTION", Value=7)]
      ACTION = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATUS", Value=8)]
      STATUS = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KILL_SPECIAL", Value=9)]
      KILL_SPECIAL = 9
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskGoal")]
  public partial class TaskGoal : global::ProtoBuf.IExtensible
  {
    public TaskGoal() {}
    
    private int _minTime = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"minTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minTime
    {
      get { return _minTime; }
      set { _minTime = value; }
    }
    private TaskLocation _location = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"location", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TaskLocation location
    {
      get { return _location; }
      set { _location = value; }
    }
    private GoalCondition _condition = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"condition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GoalCondition condition
    {
      get { return _condition; }
      set { _condition = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskSubimitPolicy")]
  public partial class TaskSubimitPolicy : global::ProtoBuf.IExtensible
  {
    public TaskSubimitPolicy() {}
    
    private int _guideID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guideID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guideID
    {
      get { return _guideID; }
      set { _guideID = value; }
    }
    private TaskSubimitPolicy.SubmitType _submitType = TaskSubimitPolicy.SubmitType.AUTO;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"submitType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TaskSubimitPolicy.SubmitType.AUTO)]
    public TaskSubimitPolicy.SubmitType submitType
    {
      get { return _submitType; }
      set { _submitType = value; }
    }
    private TaskLocation _location = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"location", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TaskLocation location
    {
      get { return _location; }
      set { _location = value; }
    }
    private int _submitFuncID = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"submitFuncID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int submitFuncID
    {
      get { return _submitFuncID; }
      set { _submitFuncID = value; }
    }
    private int _finishFuncID = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"finishFuncID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int finishFuncID
    {
      get { return _finishFuncID; }
      set { _finishFuncID = value; }
    }
    private string _storyName = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"storyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string storyName
    {
      get { return _storyName; }
      set { _storyName = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"SubmitType")]
    public enum SubmitType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AUTO", Value=0)]
      AUTO = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NPC", Value=1)]
      NPC = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskAward")]
  public partial class TaskAward : global::ProtoBuf.IExtensible
  {
    public TaskAward() {}
    
    private int _showItemID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"showItemID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int showItemID
    {
      get { return _showItemID; }
      set { _showItemID = value; }
    }
    private int _dropID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dropID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dropID
    {
      get { return _dropID; }
      set { _dropID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskInfo")]
  public partial class TaskInfo : global::ProtoBuf.IExtensible
  {
    public TaskInfo() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private TaskInfo.TaskType _type = TaskInfo.TaskType.MAIN;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TaskInfo.TaskType.MAIN)]
    public TaskInfo.TaskType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private TaskInfo.TaskCategory _category = TaskInfo.TaskCategory.GENERAL;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TaskInfo.TaskCategory.GENERAL)]
    public TaskInfo.TaskCategory category
    {
      get { return _category; }
      set { _category = value; }
    }
    private string _typeIcon = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"typeIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string typeIcon
    {
      get { return _typeIcon; }
      set { _typeIcon = value; }
    }
    private TaskInfo.ShowArea _showArea = TaskInfo.ShowArea.SHOW_EVERYWHERE;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"showArea", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TaskInfo.ShowArea.SHOW_EVERYWHERE)]
    public TaskInfo.ShowArea showArea
    {
      get { return _showArea; }
      set { _showArea = value; }
    }
    private string _mainTitle = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"mainTitle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mainTitle
    {
      get { return _mainTitle; }
      set { _mainTitle = value; }
    }
    private string _mainWord = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"mainWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mainWord
    {
      get { return _mainWord; }
      set { _mainWord = value; }
    }
    private string _mainDesc = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mainDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mainDesc
    {
      get { return _mainDesc; }
      set { _mainDesc = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _desc = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private TaskCondition _condition = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"condition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TaskCondition condition
    {
      get { return _condition; }
      set { _condition = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _prev = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"prev", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> prev
    {
      get { return _prev; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _next = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(13, Name=@"next", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> next
    {
      get { return _next; }
    }
  
    private TaskAcceptPolicy _acceptPolicy = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"acceptPolicy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TaskAcceptPolicy acceptPolicy
    {
      get { return _acceptPolicy; }
      set { _acceptPolicy = value; }
    }
    private readonly global::System.Collections.Generic.List<TaskGoal> _goals = new global::System.Collections.Generic.List<TaskGoal>();
    [global::ProtoBuf.ProtoMember(15, Name=@"goals", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TaskGoal> goals
    {
      get { return _goals; }
    }
  
    private TaskSubimitPolicy _submitPolicy = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"submitPolicy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TaskSubimitPolicy submitPolicy
    {
      get { return _submitPolicy; }
      set { _submitPolicy = value; }
    }
    private TaskLimit _taskLimit = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"taskLimit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TaskLimit taskLimit
    {
      get { return _taskLimit; }
      set { _taskLimit = value; }
    }
    private TaskAward _award = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"award", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TaskAward award
    {
      get { return _award; }
      set { _award = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"TaskType")]
    public enum TaskType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAIN", Value=0)]
      MAIN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BRANCH", Value=1)]
      BRANCH = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REPEAT", Value=2)]
      REPEAT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SPECIAL", Value=3)]
      SPECIAL = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TaskCategory")]
    public enum TaskCategory
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GENERAL", Value=0)]
      GENERAL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY", Value=1)]
      ACTIVITY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FESTIVAL", Value=2)]
      FESTIVAL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUIDE", Value=3)]
      GUIDE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCHOOL", Value=4)]
      SCHOOL = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUP", Value=5)]
      GROUP = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ShowArea")]
    public enum ShowArea
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOW_EVERYWHERE", Value=1)]
      SHOW_EVERYWHERE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOW_NOT_IN_ACTIVITY", Value=2)]
      SHOW_NOT_IN_ACTIVITY = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllTaskInfos")]
  public partial class AllTaskInfos : global::ProtoBuf.IExtensible
  {
    public AllTaskInfos() {}
    
    private AllStringID _stringID = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stringID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AllStringID stringID
    {
      get { return _stringID; }
      set { _stringID = value; }
    }
    private readonly global::System.Collections.Generic.List<TaskInfo> _taskinfos = new global::System.Collections.Generic.List<TaskInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"taskinfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TaskInfo> taskinfos
    {
      get { return _taskinfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}