//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: WordData.proto
namespace WordData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AllWordData")]
  public partial class AllWordData : global::ProtoBuf.IExtensible
  {
    public AllWordData() {}
    
    private readonly global::System.Collections.Generic.List<WordData> _tlist = new global::System.Collections.Generic.List<WordData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<WordData> tlist
    {
      get { return _tlist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WordData")]
  public partial class WordData : global::ProtoBuf.IExtensible
  {
    public WordData() {}
    
    private int _key = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int key
    {
      get { return _key; }
      set { _key = value; }
    }
    private string _stringValue = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stringValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stringValue
    {
      get { return _stringValue; }
      set { _stringValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}